### ISSUE TITLE
UMD build

### ISSUE THREAD

**Issue by DomKM** [relay-tools/react-router-relay#101]
Could you provide a UMD build like `react-relay` and `react-router` do? It would be great if `react-router-relay` could be used alongside them without requiring NPM.

**Comment by taion** [comment]
There's no point – you can't meaningfully use Relay without a Babel build step anyway.

**Comment by DomKM** [comment]
@taion Sorry, but yes, there is. See this Scala macro https://github.com/chandu0101/sri/blob/master/relay/src/main/scala/sri/relay/macros/RelayMacro.scala which shells out to Webpack/Babel to compile `Relay.QL` query strings during build time. I am doing a similar thing with Clojure. Without a UMD build, this library is completely inaccessible. Note that, as mentioned above `react-relay` already provides a UMD build.

**Comment by taion** [comment]
You're still calling into npm: https://github.com/chandu0101/sri/blob/master/relay/src/main/scala/sri/relay/macros/RelayMacro.scala#L106

And it's still using webpack and Babel. So just bundle your code properly.

**Comment by DomKM** [comment]
That macro is only calling into NPM to compile `Relay.QL`. No runtime dependencies require NPM, Webpack, or Babel, in order to bundle them.

Since I am not familiar with this ecosystem, is it difficult to provide a UMD build?

**Comment by taion** [comment]
It's just annoying.

You can't write raw JS that produces anything that Relay can deal with, so either way you're dealing with a build step of some sort – in which case you may as well set up a proper build step.

It's not like with React where with the JSX transformer, you can just throw some stuff into a JS file and drop it in a `<script>` tag to get things working. There's just no real use case here, as far as I'm concerned.

**Comment by DomKM** [comment]
As a hack to use Relay, I am shelling out to NPM once for every `Relay.QL` query string. NPM doesn't compile the project or deal with `require`s or anything significant. It's just a hack until Relay removes the Babel dependency and provides a stand-alone compilation method.

I do have a proper build step. It uses ClojureScript and the Google Closure Compiler (probably the most advanced JS compiler in the world). Essentially, JS that is compatible with Google Closure is minified in a very sophisticated way (dead code elimination, automatic rewriting, etc.), while JS that is not compatible with Google Closure is concatenated and prepended in dependency order. The non-compatible JS cannot depend on Node/NPM. It needs to be plain JS (UMD or similar).

Please realize that NPM/Webpack is not the only build tool out there. This library is literally the only runtime dependency I want to use that doesn't provide a UMD build. `react`, `react-relay`, `react-router`, `react-bootstrap`, `react-router-bootstrap`, `classnames`, etc. **all** provide UMD builds. I am trying to improve the usability of Relay via ClojureScript and would greatly appreciate a UMD build of this library.

**Comment by taion** [comment]
What? You're using the UMD build for React-Bootstrap and React Router, but you care about bundle size enough to use the Closure Compiler?

That's a deeply awful way to set up your build pipeline. You end up pulling in the entirety of React-Bootstrap, which for any reasonable application is almost certain to far outweigh any benefits you get from using the Closure Compiler.

As a maintainer on React Router, React-Bootstrap, and React-Router-Bootstrap, I strongly recommend against using the UMD bundles except in the case when you're throwing up something extremely quick and dirty in the browser.

It's a deeply suboptimal way to use those libraries for anything real, and borderline just should not be used if you have the capacity to use a real build/bundle step.

**Comment by DomKM** [comment]
I don't care about the bundle size. I'm using Google Closure Compiler because ClojureScript uses it. That was not the primary point of my response above. My point was that this library, unlike all the other libraries listed above, is not usable except via NPM. I am requesting (begging, at this point) that you will address it.

**Comment by currentoor** [comment]
@taion I can see how you'd come to this conclusion but I think you might have misunderstood how that particular ecosystem works.

Clojurescript uses the Closure Compiler internally, you have to opt out of using it rather than opt in. There is very little setup needed, essentially just a compiler config flag. The UMD option is a tradeoff for when we don't want to re-invent the wheel and are willing to put up with a reasonably larger build for it. It's worked well for a significant number of cljs projects over the past few years.

Talented people like you have built these amazing libs, and we in the cljs community want to stand on your shoulders, so to speak. By providing UMD builds you empower us and many other compile to JS communities to building more ambitious applications.

As for what's deeply awful/suboptimal, I believe that depends on a bunch of different variables so it's hard to be judgemental so quickly. For example, I would rather use React Bootstrap than build all those components myself from scratch, even if it takes a few seconds longer to initially load my app.

I implore you to at least consider a PR for creating a UMD build.

**Comment by taion** [comment]
Yes – but I've given you a number of reasons why it's not relevant here.

You need a build step anyway to make any use of Relay at all, so UMD builds for Relay aren't useful in the case of setting up a project without tooling.

If you have a build step, then you should try very hard to not use the UMD bundles for most of the third-party libraries for React. We've gone through quite a lot of trouble to set up and document best practices when using CJS modules (e.g. https://github.com/reactjs/react-router/blob/master/docs/guides/MinimizingBundleSize.md) or ES2015 modules.

If your build system is incapable of using CJS modules, then that's a prominent missing feature in your build system. Pulling in a UMD bundle to get around that is a pretty awful workaround.

**Comment by taion** [comment]
@currentoor I'd be happy to accept a PR that sets up a UMD build. I'm just not going to do it myself.

**Comment by currentoor** [comment]
@taion, that's more than reasonable. Thanks!

**Comment by taion** [comment]
To give you an idea of the numbers, the most recent `react-bootstrap.min.js` that I pushed to npm is 182 kB. That's quite a lot – especially if you're not using overlays, you'd probably only pull in < 10 kB (post-minification) worth of JS from that package for the components that you actually need.

That's the main reason we strongly recommend importing from `react-bootstrap/lib` there when using npm: http://react-bootstrap.github.io/getting-started.html.

If you are using something like React-Bootstrap (or React Router, which also pulls probably ~50 kB worth of extra history implementations), I'd even consider doing something like setting up a separate project that re-exports just the modules that you need into a browser global bundle, or something equivalent.

Actually pulling in the UMD bundles for these libraries is really not ideal, and while we do keep those bundles around, they're much more for direct consumption from `<script>` tags – i.e. we reserve the right to move them to something like Rollup and have them just declare browser globals or something.
