### ISSUE TITLE
Add Flow annotations

### ISSUE THREAD

**Issue by cpojer** [relay-tools/react-router-relay#11]
I think this is the next big thing we should add to this repo. Relay is fully typed with Flow and we should make that a standard for library around Flow.

**Comment by devknoll** [comment]
:+1:

**Comment by taion** [comment]
Why close this? I can't claim that it's a high priority for me, but I'd like to use Flow at some point.

**Comment by cpojer** [comment]
just figured no one is working on it and there is no point in keeping the issue around :) feel free to reopen.

**Comment by taion** [comment]
AFAIK nobody's working on any of the issues on the repo right now :D

Gonna re-open this, thanks!

**Comment by taion** [comment]
I'm going to close this out again.

Unfortunately Relay doesn't actually ship its Flow definitions, so I have no good way of making sure that any type checks I add here are consistent with what Relay has.

I'll look at this again once the Flow ecosystem has a better story around packages that use Flow also shipping Flow type definitions, with an eye especially on how https://github.com/graphql/graphql-js/pull/412 pans out.
