### ISSUE TITLE
Multiple params in one route

### ISSUE THREAD

**Issue by prewk** [relay-tools/react-router-relay#112]
Hi, thanks for this great lib!

Since Relay (at the moment) doesn't support nested Route queries it's really hard to support routes of this kind: `:language/post/:id` (It's a system where a single post can have languages)

I've read through https://github.com/facebook/relay/issues/112 and there seems to be some movement.

Do you have any suggestions on how to work around it? Obviously I can't use a global viewer query's "posts" as the issue suggests, because that would mean fetching 100 posts before picking the right one in JS..

Can I get the router params into the Relay Container in my component somehow? That way I can do the `post(id: $id) { ... }` query there instead. Or do I need to do a raw `location.href` parse?

I'm also wondering if nested routes are intended to compose its Route queries or if they're just hard resets on every route?

**Comment by taion** [comment]
You can pass through the variables into your child components. For example, you can use a global viewer query, and then in your component do:

```js
Relay.createContainer(PostPage, {
  initialVariables: {
    postId: null,
    language: null,
  },

  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        post(postId: $postId, language: $language) {
          whatever,
        },
      }
    `,
  },
});
```

Assuming that's what your schema looks like. I'd consider structuring this with `post(postId: $postId)` as a top-level field, and qualifying other nested fields with the relevant language, though, assuming this is some internationalized thing, or else using nesting in some other way.

**Comment by prewk** [comment]
Ah, I didn't know the variables were sent to child Relay containers as well! This solves my probem, thank you!
