### ISSUE TITLE
Support async React Router components

### ISSUE THREAD

**Issue by JeremyRylan** [relay-tools/react-router-relay#12]
React Router now has the ability to do code splitting via Webpack fairly easily (https://github.com/rackt/react-router/tree/master/examples/huge-apps).

When I try using the following code with react-router-relay, I get duplicate HTTP requests to /graphql when I navigate to the `/widget/:id` route.

```
let Routes = {
  childRoutes: [
    { name: 'home',
      path: '/',
      component: App,
      queries: HomeQueries
    },
    { name: 'widget',
      path: '/widget/:id',
      queries: WidgetQueries,
      getComponents (cb) {
        require.ensure([], (require) => {
          cb(null, require('./components/Widget'))
        })
      }
    }
  ]
};

ReactDOM.render(
  <Router
    history={new BrowserHistory()}
    createElement={ReactRouterRelay.createElementFunction()}
    routes={Routes}
  />,
  document.getElementById('root')
);
```

I'm trying to figure out a solution/workaround. I'll update the discussion with my findings.

**Comment by taion** [comment]
Is this on the `#next` branch? There's actually a bug right now where all queries get double-sent, per https://github.com/devknoll/relay-nested-routes/pull/10#issuecomment-133209804.

**Comment by JeremyRylan** [comment]
@taion Sorry, forgot to specify. Yes, this is on the `#next` branch. I don't get the double request if I stick to just do `{ component: require('./components/Widget'); }` instead of the code-splitting setup via the getComponents function.

**Comment by taion** [comment]
I see - in the current stable release I believe this logic: https://github.com/devknoll/relay-nested-routes/blob/2ebfd9c38ff9ee232f886c554156ca88d9d3961d/src/index.js#L11-L13 prevents that from happening.

However, I don't think we have either this check or the old caching logic in the current `#next` branch.

**Comment by JeremyRylan** [comment]
@taion That looks to be the problem. I gave it a shot modifying `src/containerUtils.js` in the `#next` branch and solved the issue by adding the following snippet to the very beginning of the  `createContainerElement` method:

```
  if (props.isTransitioning) {
    return null;
  }
```

It had to explicitly be `return null`. Just using `return` without `null` resulted in an error: `Invariant Violation: The root route must render a single element`.

Normally I would just go ahead and fire up a pull request, but considering how much rapid development is going on with this project right now, I don't know if it would be helpful or if you guys already have a better idea in mind. Definitely let me know if you want a PR and I'll create one.

**Comment by taion** [comment]
That's not the right solution here - it would blank out the document every time we change routes, which is not quite right.

FWIW, I would recommend using the current stable release until we've sorted everything out and cut 0.4.0 properly. It's not that big of an API change.

**Comment by JeremyRylan** [comment]
@taion I just switched back to the current stable release using the following code and the exact same issue is present. If I defined the component directly, it's only one request -- but using the getComponents function causes two HTTP requests to /graphql:

```

let Routes = {
  component: NestedRootContainer,
  childRoutes: [
    { name: 'home',
      path: '/',
      component: App,
      queries: HomeQueries
    },
    { name: 'widget',
      path: '/widget/:id',
      queries: WidgetQueries,
      getComponents (cb) {
        require.ensure([], (require) => {
          cb(null, require('./components/Widget'))
        })
      }
    }
  ]
};

ReactDOM.render(
  <Router
    history={new BrowserHistory()}
    routes={Routes}
  />,
  document.getElementById('root')
);
```

**Comment by taion** [comment]
Ah crud. Not sure why that's happening then.

If you have some chance to dig into this, could you add some debug logging to `NestedRootContainer` and figure out when `isTransitioning` gets set to false?

My assumption was that in this case, `isTransitioning` would stay true until all the async stuff was resolved, but it looks like I'm wrong - would like to understand what's happening. Won't have time to look at this myself for a bit.

**Comment by JeremyRylan** [comment]
I'll look into it later today and report back. Thank you!

**Comment by taion** [comment]
Any update on this? I might look into this at some point now that we're have v0.4.0 out.

**Comment by juhaelee** [comment]
@taion 0.4 doesnt seem to work with any of the async handlers. I took a quick look and it looks like the components that are formed using getComponents from a route need to be extracted out. This is pretty dirty but something like this maybe?

on `RouteAggregator.js` for function [`updateRoute`](https://github.com/relay-tools/react-router-relay/blob/master/src/RouteAggregator.js#L34):
```
let {component} = route;
const {getComponents} = route;
if (!component && getComponents) {
   getComponents((err, asyncComponent) => {
      component = asyncComponent;
    });
}
```

**Comment by taion** [comment]
Good catch - I don't think that's quite the right fix, though. I want to see if deeper integration into React Router is possible to address this more correctly.

**Comment by taion** [comment]
I haven't forgotten about this, BTW. I'm just waiting for the next release of R-R to land.

**Comment by taion** [comment]
I updated the title of this issue to reflect that this library currently doesn't support `getComponent` or `getComponents` at all.

**Comment by vladar** [comment]
Is there any workaround for now?

**Comment by taion** [comment]
Not really. Track https://github.com/rackt/react-router/issues/2088#issuecomment-143935473 for the upstream changes required.

**Comment by Agrosis** [comment]
+1, i like this lib, gonna revert to sync routes for now. Do you need any help with figuring out what to do here?

**Comment by taion** [comment]
No, like I said, this is blocked on changes I need to make upstream.

**Comment by cellis** [comment]
Is this still an issue? I'm trying to use `getComponent` even further downstream ( in https://github.com/denvned/isomorphic-relay-router ) and having some issues. ( `Link`s to `getComponent`ified routes reload the page, causing other issues.

**Comment by taion** [comment]
`getComponent` is fully supported here

**Comment by cartogram** [comment]
@taion what about `getComponents`? I've got `getComponent` working, but having issues with the queries when using `getComponents`.

**Comment by taion** [comment]
It's supported. You probably want to define an object for `queries` though. See the tests.

**Comment by cartogram** [comment]
Magic! Thanks!

**Comment by eysi09** [comment]
Should I not be able to pass other props such as `render` and `prepareVariables` when using a Routes object rather than jsx.

Something like:

```
    {
      path: 'mypath',
      getComponent(location, cb) {
        System.import('./components/MyComponent')
          .then(loadRoute(cb))
          .catch(errorLoading);
      },
      render: myRenderFn,
      queries: MyQueries,
    },
```
