### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by mekwall** [relay-tools/react-router-relay#126]
I'm trying to get hot reloading to work with `react-router-relay` but I can't seem to find the `replaceRoutes` method that is necessary to get `react-router` to work with hot reloading. Could you expose this method or is there an other approach on how to get hot reloading to work?

**Comment by taion** [comment]
If it's not supported in React Router, then there's nothing I can do here. Track https://github.com/reactjs/react-router/issues/2182.
