### ISSUE TITLE
[Question] Extending react router

### ISSUE THREAD

**Issue by jbaxleyiii** [relay-tools/react-router-relay#127]
Hey @taion! I was starting to work on a similar router for the [Apollo data stack](https://github.com/apollostack) and was wondering if wrapping React Router was the preferred practice?

I didn't know if there was an alternative API or middleware practice that exists, or is coming that would still allow people to import react-router but add in similar functionality to what you have done here?

Thanks!

**Comment by taion** [comment]
We just wrapped this up with an official "middleware" API for React Router. See https://github.com/reactjs/react-router/pull/3327.

**Comment by jbaxleyiii** [comment]
Thanks!

**Comment by taion** [comment]
And if you're curious, https://github.com/relay-tools/react-router-relay/pull/128 converts this library into a router middleware.
