### ISSUE TITLE
Render callbacks no longer gets routerParams as of version 0.12

### ISSUE THREAD

**Issue by ykagan** [relay-tools/react-router-relay#129]
Render callbacks (specifically renderFetched) used to get routerParams passed into them as part of the data prop. As of 0.12 this no longer happens. Specifically the change is here:

https://github.com/relay-tools/react-router-relay/commit/1c38a0e63e2e001080bfdee41ddb03da2de06097#diff-02147c9abf35e579edc77adcfc038997R44

We are using these router params to render the component (data.route.component) along with some additional data. I was wondering whether this was an intentional change, and if so what's the best way to override the rendering step now without having to declare each component twice in each route?

**Comment by taion** [comment]
That's unintentional. I'll fix it shortly.

**Comment by taion** [comment]
Released on v0.12.1 (and v0.12.2).
