### ISSUE TITLE
Make Relay environment available in router hooks

### ISSUE THREAD

**Issue by taion** [relay-tools/react-router-relay#146]
For example, I may want to check some data in an `onEnter` hook. Right now, this is only easily possible if I'm using `Relay.Store`.

**Comment by taion** [comment]
Requires https://github.com/reactjs/react-router/issues/3404.

**Comment by idris** [comment]
I have a problem where I want to return a not found (404) if something in my relay data is null.  Would this issue resolve that?

Also, you said it's possible if using Relay.Store?  How?

**Comment by taion** [comment]
Just use the `Relay.Store` singleton in your `onEnter` hook. This issue is to track providing the non-singleton `Relay.Environment` that you pass into the router.

**Comment by taion** [comment]
I'm going to close this issue because there's nothing to track here. This will fall out naturally once we resolve https://github.com/reactjs/react-router/issues/3404... and I'm not going to forget to work on this once https://github.com/reactjs/react-router/issues/3404 gets resolved, given that this is the motivation for that issue.
