### ISSUE TITLE
Multiple queries per route

### ISSUE THREAD

**Issue by sntran** [relay-tools/react-router-relay#150]
Hi there.

I'm not sure this has been addressed before but I can't find it through the issues.

```
<Router
  history={browserHistory}
  render={applyRouterMiddleware(useRelay)}
>
  <Route
    path="/:store_id" component={Store}
    queries={StoreQueries}
  >
    <IndexRoute
      component={Dashboard}
    />
    <Route
      path="inventory" component={Inventory}
      queries={StoreQueries}
    />
  </Route>
</Router>
```

My `Store` component is a layout, where it needs to display the logged in user profile's menu, as well as the store's info on the left side bar. Normally if I use Relay, I can have a `Relay.Route` with queries like this:

```
static queries = {
  viewer: (Component) => Relay.QL`
    query {
      viewer {
        ${Component.getFragment('viewer')}
      }
    }
  `,
  store: (Component) => Relay.QL`
    query {
      storeByPath(path: $path) {
        ${Component.getFragment('store')}
      }
    }
  `
};
```

However, when I try to use similar queries in my `Route`, the app does not render. Am I missing anything here?

**Comment by taion** [comment]
It wouldn't be `$path` – the name of the Relay route param would be the same as the React Router route param (`$store_id` in this case).

**Comment by sntran** [comment]
That was not an issue, but yeah, sorry, I used a old variable here. It should be `$store_id`. I have updated the issue. My `Store` just happens to have a `path` property. It's not the prop of `Route`.

My issue was having the following `StoreQueries` that won't render:

```
export default {
  viewer: (Component) => Relay.QL`
    query {
      viewer {
        ${Component.getFragment('viewer')}
      }
    }
  `,
  store: (Component) => Relay.QL`
    query {
      storeByPath(path: $store_id) {
        ${Component.getFragment('store')}
      }
    }
  `
};

**Comment by taion** [comment]
You'd also need to pass through the params as variables there for the latter query. But easier just to use the query shorthand.
