### ISSUE TITLE
Show loading indicator

### ISSUE THREAD

**Issue by nikhildaga** [relay-tools/react-router-relay#153]
I am using the [huge apps example](https://github.com/reactjs/react-router/tree/master/examples/huge-apps) code with react-router-relay.

What should I do to show loading indicator when the route is changed?
Using render or renderLoading does not work.

renderLoading has no effect.
```
module.exports = {
  path: 'home',
  queries: queries,
  renderLoading: () => <div>Loading...</div>,
  getComponent(nextState, cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/App'))
    })
  }
}

```

using render gives " Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child" error
```
module.exports = {
  path: 'home',
  queries: queries,
  render: ({ props }) => props ? require('./components/App') : <div>Loading...</div>,
  getComponent(nextState, cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/App'))
    })
  }
}

```

Thanks to NevilleS, I found my mistake. Need to spread props.
the code below works perfectly
```
module.exports = {
  path: 'home',
  queries: queries,
  render: ({ props }) => props ? <App {...props} /> : <div>Loading...</div>,
  getComponent(nextState, cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/App'))
    })
  }
}

```

**Comment by NevilleS** [comment]
We diagnosed this issue a bit - everything works fine with `render`, but you aren't passing along the props correctly to the `App` component. See https://github.com/relay-tools/react-router-relay/blob/master/README.md for usage details on how you need to spread the `props` into your component, e.g.:
```javascript
        <Route
          path=":widgetId" component={Widget}
          queries={WidgetQueries}
          render={({ props }) => props ? <Widget {...props} /> : <Loading />}
        />
```

**Comment by nikhildaga** [comment]
@NevilleS :+1:  Yes. Thank you so much for your help :)

**Comment by taion** [comment]
Separately, tracking loading state for async components/routes is more of a React Router concern than a react-router-relay concern – right now the router doesn't explicitly surface a way to notify you that async routes are resolving, but you can e.g. attach a listener to the history.
