### ISSUE TITLE
Modals and multiple routes ?

### ISSUE THREAD

**Issue by kamek-pf** [relay-tools/react-router-relay#155]
This is a question more than an issue, here's my use case :

I'm showing a list of places on a page. The query looks like that : 
```
Relay.QL`fragment on Viewer {
    places(first: 100) {
        edges {
            node {
                name
                // some other fields
            }
        }
    }
}`;
```

Now when the user clicks one of those places, I need to show some additional informations in a modal. I want to use the `node` interface to fetch the missing fields and show the response.

The query I had in mind would look something like that : 
```
Relay.QL`fragment on Node {
    ... on Place {
        gps
        // some more fields
    }
}`;
```

I can't figure out how to use both queries together, because the same view needs to use two different routes I guess.

I must be missing something really obvious since the use case is so simple, but for some reasons I've been stuck for a while and I can't see what it is.

Any idea how I should handle this ?

**Comment by NevilleS** [comment]
You can include multiple queries on your Route:
```
const ViewerQueries = {
  viewer: () => Relay.QL`query { viewer }`
};

const NodeQueries = {
  node: () => Relay.QL`query { node(widgetId: $widgetId) }`
}

// within routes
<Route
  path=":widgetId" component={Widget}
  queries={ViewerQueries, NodeQueries}
  render={({ props }) => props ? <Widget {...props} /> : <Loading />}
/>

// container is something like this
export Relay.createContainer(Widget, {
  fragments: {
    node: Relay.QL`fragment on Node { ...on Widget { ... } }`,
    viewer: Relay.QL`fragment on Viewer { ... }`
  }
})
```

This works as long as you always have a `widgetId` to form the query from. That's how you use multiple queries in the same component.

However, I think what you really want is to *conditionally* form the `node` query (e.g. send the `viewer` query first, then show the `node` query alone. Personally, I'd do that with a new RootContainer as part of something like a `WidgetModal` component:
```
// in WidgetModal
render() {
  <Relay.RootContainer
    Component={Widget}
    route={NodeQueries}
  />
}
```

**Comment by NevilleS** [comment]
Also, since you are using `react-router-relay`, if you want the modal to have a URL I'm pretty sure you can nest the `Route` definition:
```javascript
<Route
  path="/" component={WidgetList}
  queries={ViewerQueries}
>
  <Route
    path="/:widgetId" component={WidgetModal}
    queries={NodeQueries}
  />
</Route>
```

In this scenario, `WidgetModal` would be a regular container, not a component with a root container:
```javascript
// WidgetModal
export Relay.createContainer(WidgetModal, {
  fragments: {
    node: `fragment on Node { ... }`
  }
}
```

I might be misremembering though, check the docs to fix whatever errors I've included here

**Comment by taion** [comment]
:+1: to both of those. I generally make a new root container or renderer for overlays, except when they have an associated route.

**Comment by kamek-pf** [comment]
Thank you guys for your help !
I ended up experimenting a bit, creating multiple containers also works well : 
```javascript
class Places {...}

const PlaceList = Relay.createContainer(Places, {
    fragments: {
        viewer: () => PlaceBaseQuery
    }
});

const PlaceUpdate = Relay.createContainer(Places, {
    fragments: {
        viewer: () => PlaceBaseQuery,
        node: () => PlaceFullQuery
    }
});

export { PlaceList, PlaceUpdate };
```

And the routes look like this : 
```javascript
const RootQuery = {
    viewer: () => Relay.QL`query { viewer }`
};

const NodeQuery = {
    viewer: () => Relay.QL`query { viewer }`,
    node: () => Relay.QL`query { node(id: $id) }`
};

...
<Route path="places"
        component={ PlaceList}
        queries={ RootQuery } />

<Route path="places/:id"
        component={ PlaceUpdate }
        queries={ NodeQuery } />
...

```

It's nice we have a few different ways to go about this sort of things

**Comment by chrispallase** [comment]
@NevilleS @taion  

How is nested Route suppose to work with this example?
All I can pass to `node` is `id` and all it can return is` id` or `__typename`.

**Comment by unirey** [comment]
@NevilleS  @taion 

How is nested Route suppose to work with this example?
All I can pass to node is id and all it can return isid or __typename.

**Comment by unirey** [comment]
@NevilleS @taion 

How is nested Route suppose to work with this example? 
All I can pass to `node` is `id` and all it can return is `id` or `__typename`.

**Comment by taion** [comment]
Use a new Relay renderer. Pass in whatever data you need in params for the route via props.
