### ISSUE TITLE
Redirect in route render

### ISSUE THREAD

**Issue by schickling** [relay-tools/react-router-relay#156]
First of all thanks for actively maintaining this library! 👍 

I was wondering what's currently the best practise to do a redirect when a Relay route returns an error?
A minimal workaround could look like this but there has to be a better way.

```js
const render = ({ error, props, element }) => {
  if (error) {
    window.location.pathname = '/'
  }

  return React.cloneElement(element, props)
}

export default (
  <Route path='/'>
    <Route path=':id' component={RootView} queries={ViewerQuery} render={render} />
  </Route>
)
```

**Comment by taion** [comment]
I'd render a dummy component (`<RedirectOnMount to="/foo" />`) that just redirects using `context.router` when it mounts.

**Comment by schickling** [comment]
That's how I already do it but that feels like a hack tbh...

**Comment by taion** [comment]
A bit. Maybe I can inject `router` as a prop there. Or we can do https://github.com/reactjs/react-router/issues/3325#issuecomment-217730740.

**Comment by schickling** [comment]
I think having the `router` there would make a lot of sense since it save the additional render attempts.

**Comment by schickling** [comment]
Do you think it make sense to reopen this in the meanwhile?

**Comment by fabiosantoscode** [comment]
To fix this, I've created a `Redirector` component with https://www.npmjs.com/react-side-effect. It's working well, and it can be used wherever in the application.

**Comment by ramusus** [comment]
@fabiosantoscode where we can see your Redirector component?

**Comment by taion** [comment]
React Router as-is doesn't offer the necessary hooks to do this the way I want. This functionality is doable with found; see https://github.com/4Catalyzer/found-relay/pull/1.
