### ISSUE TITLE
Additional Relay query parameter causes remount of route's component

### ISSUE THREAD

**Issue by toxsick** [relay-tools/react-router-relay#158]
Hi guys,

I'm trying to implement to implement search on a connection connection, but I can't get my view to update correctly. Here is a simplified version of my relay container. 

```javascript

// ThingsList.js
class ThingsList extends React.Component {

  constructor(props) {
    console.log('IN ThingsList constructor:', props);
    super(props);
    this.handleLoadMore = this.handleLoadMore.bind(this);
    this.handleSearchSubmit = this.handleSearchSubmit.bind(this);
  }

  handleLoadMore() {
    this.props.relay.setVariables({
      count: this.props.relay.variables.count + 1
    });
  }

  handleSearchSubmit(data) {
    this.props.relay.setVariables({
      search: 'test'
    });
  }

  render() {

    console.log('IN ThingsList render');

    const rows = this.props.viewer.things.edges.map(edge => {
      return (
        <tr key={edge.node.id}>
          <td>{edge.node.id}</td>
        </tr>
      );
    });

    return (
      <div>
        <table>
          <thead>
            <tr>
              <th>id</th>
            </tr>
          </thead>
          <tbody>
            {rows}
          </tbody>
        </table>
        <Button onClick={this.handleLoadMore}>Load more</Button>
        <Button onClick={this.handleSearchSubmit}>Search</Button>
      </div>
    );
  }
}

export default Relay.createContainer(ThingsList, {
  initialVariables: {
    count: null,
    search: null
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        things(first:$count, search:$search) {
          edges {
            node {
              id
            }
          }
        }
      }
    `
  }
});
```

The route looks like this:

``` javascript

// App.js
// ...

function prepareThingsParams(params, { location }) {
  console.log('IN prepareThingsParams');
  return {
    ...params,
    search: '',
    count: 10
  };
};

render(
  <Router history={browserHistory} render={applyRouterMiddleware(useRelay)}
    environment={Relay.Store} >
    <Route path="/" component={App} queries={ViewerQueries} >
      <Route path="things" queries={ViewerQueries} component={Things}
        render={({ props }) => props ? <ThingsList {...props} /> : <Loading />}
        prepareParams={prepareThingsParams} />
    </Route>
  </Router>
  , document.getElementById('app')
);
```

Using the `Load more` button work's as expected:

1. When the `/route` is loaded relay fetches the first 10 things and renders the ThingsList component with that data. (My debug statements show me that prepareThingsParams is fired, then the ThingsList component is mounted (contructor) and finally the component is rendered (render))

2. When I click the `Load more` button, relay fetches one more item (after the last cursor) and appends it to the end of the list. I can only see my render() debug statement in the console multiple times --> I think for every state transition of the relay query..) 
3. This is what I expect!

### ISSUE: Search query triggers remount of the whole component!

I would expect my search implementation to work in a similar way, but here is what actually happens:

1. I click the search button.
2. I can see the relay query is constructed correctly with `(first:10,search:"test")` as parameters. The response from my server also looks correct and returns 10 different things as before.
3. HERE COMES THE PROBLEM: Instead of just rerendering the ThingsList component with fresh data it seems the whole component is remounted (I can see my debug statements in the prepareThingsParams, the constructor and finally the render method).

This also means that the ThingsList component looses all it's state including the search param. That's why the initial 10 things (without search) are rendered.

### BUT: When I hit search again now,...

...the data fetched before is still in the relay store and no query is triggered. Instead the view is updated correctly with the 10 things returned by the initial search query.

As you can imagine this behavior is not acceptable because all the state of my view (including the state of other components used in the view) is lost during the remount..

### Why is that?!

My impression is that it must have something to do with `react-router-relay` since my prepareThingsParams is also triggered during the remount my component. Doesn't `react-router-relay` or `relay` know how to handle my search field? But when the data is already in the relay store everything works as expected.. So what triggers the reload/remount of the whole route?!

Can someone please tell me what is going on? I desperately need some help here :(

Best regards
Hannes

**Comment by taion** [comment]
I'm not aware of anything in react-router-relay that causes this, since you're not triggering any navigation. Consider not making those variables be route params, though, and just have them be owned by the component.

**Comment by toxsick** [comment]
Hi taion,

thanks for your reply. The thing is, I only added the `prepareThingsParams ` method to see if the route is reinitialized too, which seems to be the case. If I remove the route params and just add them as `initialVariables` to the container as you advised, I get exactly the same error.

If the problem is not related to react-router-relay do you have a feeling if this is related to react-router or is it relay itself? Would be nice if you could point me in the right direction.

Thanks!

**Comment by taion** [comment]
I have no idea. It's possible that something else you're doing there is somehow causing the page to refresh or navigate.

**Comment by toxsick** [comment]
Hi taion,

thanks for your feedback. After some more digging I found the root of all evil. In my actual implementation I had an App component wrapped around my view and it did something like:

```
{React.cloneElement(this.props.children, {key: Math.random()})}
```

This is obviously not a good idea :)

THANKS!
