### ISSUE TITLE
Schema in Documentation

### ISSUE THREAD

**Issue by frankbaum** [relay-tools/react-router-relay#159]
I've just started learning GraphQL/Relay - I'm attempting to implement your react-router-relay - but from your documentation I cannot seem to figure out how to get the 'widgets/:widgetid' functionality to work I am either getting a message that the parameter/variable is undefined or 'Unknown argument' for the parameter - in looking at the referenced relay-todmvc it does not implement a similar schema with an argument etc   - in most samples there is this single driving 'viewer' or 'store' but the addition of the 'WidgetQueries' is throwing me off a bit and without the schema and/or a full working example I'm not sure how this is intended to work.

**Comment by taion** [comment]
There is a fully set up example linked in the README.
