### ISSUE TITLE
Turn a clean url segment into a global id for node field look up 

### ISSUE THREAD

**Issue by albertstill** [relay-tools/react-router-relay#16]
I would like to call a base64 function on a clean URL slug (e.g http://red-badger.com/blog/2015/07/09/graphql-and-the-open-movie-database-from-introspection-to-inception/) so I can look up our Post node using the node query field instead instead of the custom query field we made `getPostBySlug`. This would mean our SPA uses Relay's caching. Is this possible with relay-nested-routes? Do I have a hook I can use to do some computation on url segment and pass a new variable to the query? Here is the code I have at the moment. Thanks.

```js
let PostQueries = {
  post: Component => Relay.QL`
    query {
      getPostBySlug(slug: $splat) {
        ${Component.getFragment('post')},
      },
    }
  `
};

React.render(
  <Router history={new BrowserHistory()}>
    <Route component={NestedRootContainer}>
      <Route
        name="home" 
        path="/blog"
        component={PostIndex}
        queries={IndexQueries}
      />
      <Route
        name="post"
        path="/blog/*"
        component={Post}
        queries={PostQueries}
      />
    </Route>
  </Router>,
  document.getElementById('root')
);
```

**Comment by taion** [comment]
1. Pass params down to the fragment from the query
2. Use `prepareVariables` on the container holding the fragment to apply whatever transforms you want to the variables
3. Use the transformed variables in the fragment

**Comment by taion** [comment]
You'll want to use something like a root `viewer` field and attach things like `getPostBySlug` to that for this to work, BTW.

**Comment by taion** [comment]
See e.g. https://github.com/facebook/relay/issues/99, though that doesn't include the `prepareVariables` bit.

**Comment by albertstill** [comment]
Thanks for this @taion. How do I pass params down to the fragment from the query? Also we want to ditch `getPostBySlug` in favour of `node(id: $base64OfSlug`). This way we will not need to refetch data that have already been collected on the index page of the posts between Relay will see the Post is the same node it's already fetched.

**Comment by taion** [comment]
Second arg of `getFragment` is the params.

**Comment by taion** [comment]
Does that work for you?

**Comment by taion** [comment]
From @dschafer on the GraphQL Slack, directly using the `node` field appears to be an anti-pattern:

![image](https://cloud.githubusercontent.com/assets/3112159/9588732/dc75fbc4-4ff7-11e5-8067-5c614bbce363.png)

The broader use case is documented on #29.

**Comment by taion** [comment]
BTW, since `node` is a root field, you actually can't do this via variables or `prepareVariables`. There's intentionally no equivalent `prepareParams` hook because it seems like this is the only real use case, and it's a bit of an anti-pattern per the above.

If you really must translate a local ID into a global ID, I'd just sneak the ID into `location.query` in an `onEnter` hook or something. The right thing to do is to wait for progress on https://github.com/facebook/relay/issues/75, and use that mechanism when it becomes available, rather than breaking the opacity of global IDs on the client side.

/cc @KyleAMathews

**Comment by KyleAMathews** [comment]
btw, mutating `location.query` in `onEnter` to generate the opaque id for the node argument totally works :) I'm not entirely sure figuring this out was worth the couple of hours it took but I really love my route transitions being ~instantaneous now.
