### ISSUE TITLE
Docs out of date (?) 

### ISSUE THREAD

**Issue by brettjashford** [relay-tools/react-router-relay#160]
the docs say to 
```js
import useRelay from 'react-router-relay';
```
but `react-router-relay'` only exports `renderRouterContext` and `renderRouteComponent`. (https://github.com/relay-tools/react-router-relay/blob/v0.13.2/src/index.js#L8)

i'd very much appreciate updated docs or even a link to an example.

**Comment by taion** [comment]
The example in the README is up-to-date and correct.
