### ISSUE TITLE
Proxied components in routes yield invariant violation for ReactRouterProxy

### ISSUE THREAD

**Issue by rosskevin** [relay-tools/react-router-relay#161]
`Uncaught Invariant Violation: relay-router-relay: Route with queries specifies component ReactRouterProxy that is not a Relay container.`

From this [code](https://github.com/relay-tools/react-router-relay/blob/master/src/QueryAggregator.js#L73)

---------
## Background
I want to use jsx syntax for routes for readability, but make sure not to lose any code splitting benefits.  So far, this has worked well using https://github.com/luqin/react-router-loader.  The code is **much** more readable for me, and would very much prefer to stay with this.  I'm just getting started down the relay path so I have a repo setup with my experiments, trying to blend together everything into a workable demo.

## Old route code
_yuck_
```javascript
import ViewerQueries from '../../queries/ViewerQueries'

export default {
  path: '/todos',
  getComponent: (nextState, cb) => {
    require.ensure([], (require) => {
      cb(null, require('./components/TodoApp').default)
    })
  },
  queries: ViewerQueries,
  indexRoute: {
    getComponent: (nextState, cb) => {
      require.ensure([], (require) => {
        cb(null, require('./components/TodoList').default)
      })
    },
    queries: ViewerQueries,
    prepareParams: () => { status: 'any' }
  },
  childRoutes: [
    {
      path: ':status',
      getComponent: (nextState, cb) => {
        require.ensure([], (require) => {
          cb(null, require('./components/TodoList').default)
        })
      },
      queries: ViewerQueries
    }
  ]
}
```

## New route [code](https://github.com/rosskevin/my-relay-starter-kit/blob/master/src/routes/todos/index.js#L22)
_yielding the error_, but **much more readable!** _yay!_
```javascript
import ViewerQueries from '../../queries/ViewerQueries'
import React from 'react'
import {Route, IndexRoute} from 'react-router'
import TodoApp from 'react-router!./components/TodoApp'
import TodoList from 'react-router!./components/TodoList'

function prepareIndexParams (params, { location }) {
  console.log(`location? ${location}`)
  return {
    ...params,
    status: 'any'
  }
}

export default (
  <Route path='/todos' component={TodoApp} queries={ViewerQueries}>
    <IndexRoute component={TodoList} queries={ViewerQueries} prepareParams={prepareIndexParams} />
    <Route path=':status' component={TodoList} queries={ViewerQueries} />
  </Route>
)
```

## Demo
1. setup/install

  ```bash
git clone https://github.com/rosskevin/my-relay-starter-kit
cd my-relay-starter-kit
npm install
npm start
  ```

1. Open browser, click `todos`, it will yield the error  
1. All other links are non-relay and are routable

----
## Question

Is this something I can work around? Does it require a change in react-router-relay or the proxy creator code react-router-loader?

**Comment by rosskevin** [comment]
FYI This alternate works, but I would still **much prefer avoiding this** superfluous `getComponent` code:

```javascript
import ViewerQueries from '../../queries/ViewerQueries'
import React from 'react'
import {Route, IndexRoute} from 'react-router'

function prepareIndexParams (params, { location }) {
  console.log(`location? ${location}`)
  return {
    ...params,
    status: 'any'
  }
}

export default (
  <Route path='/todos' getComponent={
    (nextState, cb) => {
      require.ensure([], (require) => {
        cb(null, require('./components/TodoApp').default)
      })
    }
  } queries={ViewerQueries}>

    <IndexRoute getComponent={
      (nextState, cb) => {
        require.ensure([], (require) => {
          cb(null, require('./components/TodoList').default)
        })
      }
    } queries={ViewerQueries} prepareParams={prepareIndexParams} />

    <Route path=':status' getComponent={
      (nextState, cb) => {
        require.ensure([], (require) => {
          cb(null, require('./components/TodoList').default)
        })
      }
    } queries={ViewerQueries} />
  </Route>
)
```

**Comment by taion** [comment]
That proxy is not equivalent to `getComponent`, which is why it isn't working here. Whatever you declare as `component` or return from `getComponent` has to be a Relay container so we can build the full query. These wouldn't work as the children of Relay components either.
