### ISSUE TITLE
Unable to get variable in fragment

### ISSUE THREAD

**Issue by nikhildaga** [relay-tools/react-router-relay#167]
index.js
```
import React, { PropTypes } from 'react';
import Relay from 'react-relay';
import app from './app';

const queries = {
  viewer: (Component, variables) => Relay.QL`
    query {
      viewer{
        ${Component.getFragment('viewer', variables)}
      }
    }
  `,
};

module.exports = {
  path: 'post/:id',
  queries,
  getComponent(nextState, cb) {
    require.ensure([], () => {
      cb(null, app);
    });
  },
};
```
app.js
```
const App = Relay.createContainer(AppComponent, {
  initialVariables: {
    id: null,
  },
  fragments: {
    viewer: (variables) => Relay.QL `
      fragment on viewer {
        post(id: $id) {
          title,
        }  
      }
    `,
  },
});
```

This doesn't work. What am I doing wrong here? I have gone through readme and tried several things but still have not been able to get it to work.

Please help. :)

**Comment by taion** [comment]
See multiple previous issues: https://github.com/relay-tools/react-router-relay/issues/53, https://github.com/relay-tools/react-router-relay/issues/57, https://github.com/relay-tools/react-router-relay/issues/58, &c.

**Comment by nikhildaga** [comment]
Thanks. I found out the problem. Not sure if its related to those issues.

If the path is post/1  , the variable passed to fragment is "1"
In my schema I has set the argument id as GraphQLInt. Had to change it to GraphqlString.
