### ISSUE TITLE
How do I map a clean URL to an opaque Relay id?

### ISSUE THREAD

**Issue by coolov** [relay-tools/react-router-relay#170]
Let say that the url path `/2005/12/01/this-is-a-unique-and-pretty-url.html` maps to a response with UID `100000004122287`.

- When I enter via a deep link, I would like my query to be something like:  
`myQuery(id: "/2005/12/01/this-is-a-unique-and-pretty-url.html") { field }`
- But if I enter via a react-router `<Link>` I would like my query to be:  
`node(id: "100000004122287") { field }`

The second scenario would allow Relay to look in it's local cache before attempting another round trip.

This seems like a common use case. Is there a proper/recommended way to map a URL to an opaque id?

Related https://github.com/relay-tools/react-router-relay/issues/16

**Comment by taion** [comment]
Use location state and `getQueries`.

**Comment by matthewjohnston4** [comment]
Apologies for commenting on something closed so long ago, but are there any examples of the above solution in action? None of the sample apps use it, and it's pretty unclear from the brief mention in the readme for a noob like me.

**Comment by coolov** [comment]
Something like this should work ...

Pass the Relay id in to the React Router `<Link>` component
```javascript
const linkTo = {
  pathname: pathname,
  state: { relayId: id },

<Link to={linkTo} />
```
And then look for state in the router and use either the root query or the node root query. 
```javascript
<Route
  path="/*.html"
  getQueries={({ location }) => (location.state ?
     { page: () => Relay.QL`query { node(id: $id) }` } :
     { page: () => Relay.QL`query { page(id: $id) }` })
   }
  prepareParams={({ slug, ...otherParams }, { location }) => {
     const id = (location.state && location.state.relayId) ?
       location.state.relayId :
       slug;
     return { id, ...otherParams };
  }}
/>
```

**Comment by vadimshvetsov** [comment]
@coolov And why do you pass slug as an id if there is no relayId in the location.state?

**Comment by coolov** [comment]
@vadimshvetsov this is for direct links, where the slug is known but not the relay id

**Comment by vadimshvetsov** [comment]
@coolov Thanks for replying, but I really can't understand how slug as id helps find direct links... Did you implemented a function in pageType resolver, which checking id whether id or slug there and then make db check?

**Comment by coolov** [comment]
Assets can be resolved by slug in my graphql schema. The app is isomorphic/universal. 

- All direct links are server rendered and based from the `slug` (url path)
- All "soft links" (client side links via push state) are resolved from the relay id
