### ISSUE TITLE
Progress bar on Route changes

### ISSUE THREAD

**Issue by papigers** [relay-tools/react-router-relay#171]
I'm trying to implement progress display on route changes: I have functions `start` and `done`.
Starting is not an issue, just implement react router's  `onUpdate` or `transitionListener` hooks,  and I'm good. 

The problem is ending the progress. Is there a simple way for doing that globally, for every route render (like global render function that will call `done` when the fetching is done)? 

Note that I don't actually mean the regular relay render function since I don't want to return a component. Just to simply run code after every fetch is complete. 

Thanks

**Comment by taion** [comment]
Use your component mount hooks or call something in `render`; there's no reason to have a special lifecycle hook for this.
