### ISSUE TITLE
improve README to explain where applyRouterMiddleware come from?

### ISSUE THREAD

**Issue by gre** [relay-tools/react-router-relay#180]
I guess it's from react-router, but in all the code sample in the README it's undefined.

adding the import would help getting started.

**Comment by taion** [comment]
Well, so are all the other router-related imports, though.

I wonder if the issue is more the docs on React Router?

**Comment by gre** [comment]
I usually except getting started code to be complete. Of course yeah we can explore more docs, but I think it is better for new user that a code can be just dropped in and it works.

**Comment by gre** [comment]
especially for everything related to imports.

**Comment by gre** [comment]
applyRouterMiddleware is part of the "how to use this lib"

**Comment by taion** [comment]
I mean the issue essentially is that the right way to write those imports looks like:

```js
import applyRouterMiddleware from 'react-router/lib/applyRouterMiddleware';
import IndexRoute from 'react-router/lib/IndexRoute';
import Route from 'react-router/lib/Route';
import Router from 'react-router/lib/Router';
```

which is a _lot_ of boilerplate.

**Comment by gre** [comment]
maybe just

```js
import {applyRouterMiddleware,...} from 'react-router';
```

applyRouterMiddleware is an hidden feature of react-router, so better say where it is, VS the *Route being the basic usage of react-router (so for these, make sense to not mentioned them)

**Comment by gre** [comment]
anyway. if you think it's useless. feel free to close this issue, people will still find it when googling..

**Comment by taion** [comment]
I agree that `applyRouterMiddleware` is under-documented. I just wonder if I'd be better off adding more docs on the React Router side.

**Comment by elado** [comment]
I use

```js
import { Router, Route, IndexRoute, Link, browserHistory, applyRouterMiddleware } from 'react-router'
```

Totally agree this should be on react-router-relay docs. `applyRouterMiddleware` might not be relevant to `react-router`'s getting started guide, but it's definitely necessary here. When I started with relay router it took me a few minutes/googling to figure out where this function comes from.

**Comment by taion** [comment]
That's part of the problem though. That's not the right way to import stuff from React Router unless you're using babel-plugin-lodash.

It _should_ be

```js
import Router from 'react-router/lib/Router';
```

but I don't want a half-dozen lines of that sort of router import at the top of my example, and I don't want to demonstrate an incorrect import style for another library either.

**Comment by taion** [comment]
Well, I guess how you do imports from React Router is not the concern of _this_ library. And I do the same thing on react-router-scroll anyway.
