### ISSUE TITLE
Something strange with `default` in `import useRelay from 'react-router-relay';`

### ISSUE THREAD

**Issue by nodkz** [relay-tools/react-router-relay#192]
I'm started develop [relay-northwind-app](https://github.com/nodkz/relay-northwind-app/commit/86cfe0323494b23a7502f73c8635e92eeb479cc0) example app about 10 days ago.

All works perfectly before I make it public and got responses that it does not work. Crashed with  the following error:
<img width="1179" alt="screen shot 2016-08-29 at 11 19 39" src="https://cloud.githubusercontent.com/assets/1946920/18041503/9b89a306-6ddb-11e6-9134-dba013df7777.png">

**Comment by taion** [comment]
It's because of https://github.com/nodkz/relay-northwind-app/blob/dd59c2e55d899dd8cdfb2d36571b5c4f4f5418d5/.babelrc#L28

react-router-relay exposes an ES2015 module build. If you're using webpack 2, but have module transpilation turned on in Babel, you're going to get the above error.

I added that invariant in React Router exactly to catch this case.

**Comment by nodkz** [comment]
After reinstall `node_modules` from scratch I got same error. `react-router`, `react-router-relay` did not change. So I think that was changed some internal babel dependency (now will use `shrinkwrap`).

So problem soved by
```js
applyRouterMiddleware(useRelay.default ? useRelay.default : useRelay
```

... got answer! @taion thanks!

**Comment by nodkz** [comment]
@taion definitely needs an ability to setup env via `babel-loader` options: https://github.com/babel/babel-loader/issues/283

**Comment by taion** [comment]
Personally, I just don't transpile modules for my Node scripts in projects where I use webpack 2. Actually I don't really use Babel there at all in many cases given the broad ES2015 support in Node 6.

**Comment by nodkz** [comment]
Did you somehow alive `import/export` for Node 6? 

How I know V8 does not support it yet. And `Chakra` is not my way.

PS. I'm using HMR on client/server, so for proper work of `babelRelayPlugin` on my code under webpack, I should use babel for it. Otherwise, needs to rewrite all app from `import` to `require` (but this is crazy).

**Comment by taion** [comment]
Oh, in that case consider using a server webpack bundle perhaps.

**Comment by nodkz** [comment]
Already use it.
Anyway, all works now. Will wait for V8 with imports, for removing `applyRouterMiddleware(useRelay.default)` hack with my build routine.

Thanks!

**Comment by taion** [comment]
You could also drop `module` from `mainFields` in your webpack config. As-is, everything that actually has an ES module build under `module` will break in the same way if you try to use default imports.

**Comment by grahamb** [comment]
I'm seeing this as well with Webpack 2. I have module compilation disabled in my babel-loader config: https://github.com/sfu/student-dashboard/blob/router/webpack.config.js#L53

Any ideas?

**Comment by taion** [comment]
You need to disable the use of `.babelrc` in your Babel loader.

**Comment by grahamb** [comment]
Well, that was easy. Thanks!
