### ISSUE TITLE
Strange GraphQL query

### ISSUE THREAD

**Issue by johntran** [relay-tools/react-router-relay#196]
Status Code 400
```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:7) Expected {, found $\n\n1: query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[4]_@@default_viewer {\n         ^\n2:   viewer {\n",
      "locations": [
        {
          "line": 1,
          "column": 7
        }
      ],
      "stack": [
        "GraphQLError: Syntax Error GraphQL request (1:7) Expected {, found $",
        "",
        "1: query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[4]_@@default_viewer {",
        "         ^",
        "2:   viewer {",
        "",
...
      ]
    }
  ]
}
```

GraphQL query by Relay Router:
```
"query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[3]_@@default_viewer-$$_route[4]_@@default_viewer {
  viewer {
    ...F8
  }
"
```

Expected query:
```
"query ViewerQuery {
  viewer {
    ...F8
  }
}"
```

How I came across this:
There are two routes specified under Routes.js. I type in the url for Route1. Then I go to Route2, set off a Login Mutation, and I get the above error. If I stay on Route2 and refresh the page, the Login is successful. If I look at the backend, changes were made, so the mutation was successful. It is just the fetching of data that fails.

How can I go forward from here? Thanks!

**Comment by taion** [comment]
Are you using a custom network layer?

**Comment by johntran** [comment]
We are using a custom network layer on production, but not on development. It breaks like this on both environments.

I found out that upgrading "react-relay" 0.9.2 to 0.9.3 breaks it. 

Downgrading to 0.9.2 shows no errors and fixes this issue.

graphql-relay 0.4.3 is fine and doesn't break anything.

Let me know if you need more information

**Comment by nodkz** [comment]
I can confirm this problem. I got similar error after Relay upgrading till 0.9.3
Sorry, but I have no time for detailed investigation right now.

**Comment by taion** [comment]
Presumably it's https://github.com/facebook/relay/commit/de95499215827667b301160588976f2d3355dee6, but I'm not sure why I didn't see this in my code.

**Comment by taion** [comment]
Or why the tests still pass.

**Comment by taion** [comment]
Can one of you test https://github.com/relay-tools/react-router-relay/pull/197 and let me know if it works? I can't figure out how to trigger the error on my end.

**Comment by johntran** [comment]
I'll test it tonight. :)

**Comment by johntran** [comment]
This fixed the case. You can close this after you merge it in :).

👍 👍 👍 👍 👍 👍
