### ISSUE TITLE
Allow the Router environment to be dynamically changed

### ISSUE THREAD

**Issue by walterbm** [relay-tools/react-router-relay#199]
Not sure if this is a bug or if I have simply not configured my `Router` correctly.

```
<Router history={hashHistory} render={applyRouterMiddleware(useRelay)} environment={environment}>
<Route path="/" component={App} queries={RootQuery}>
			<Route path="/logout" onEnter={(next, replace) => {
				environment = new Relay.Environment();
				}
			}/>
	</Router>
```

**Comment by taion** [comment]
You need to actually re-render the relevant elements. Wrap this in a React component that uses `state` or something.

**Comment by walterbm** [comment]
Thanks for the quick feedback. I accidentally submitted the issue too early. 

So the `Router` component needs to be re-rendered?

**Comment by walterbm** [comment]
For anyone that may be have stumbled into a similar problem, this is how I fixed it. 

```javascript
export default class RouterWrapper extends React.Component {
  constructor() {
    super();
    let environment = new Relay.Environment();
    this.state = { environment: environment }
  }
  render() {
    return (
      <Router history={hashHistory} render={applyRouterMiddleware(useRelay)} environment={environment}>
        <Route path="/" component={App} queries={RootQuery}>
        <Route path="/logout" onEnter={
          (next, replace) => { this.setState({environment = new Relay.Environment()})
        }}/>
      </Router>
  }
}
```

**Comment by pedro-ribeiro** [comment]
@walterbm, is that solution working when it comes to mutations?

When configuring a custom Network Layer (new-environment.injectNetworkLayer(...)), mutations still fallback to the default network layer implementation.

I am really struggling with this. :(

**Comment by skoushan** [comment]
@pedro-ribeiro see https://github.com/facebook/relay/issues/1494. There is a bug in Relay Classic that could be causing your component to use the old environment instead of the new one.
