### ISSUE TITLE
Not combining ALL active routes?

### ISSUE THREAD

**Issue by unirey** [relay-tools/react-router-relay#201]
Im trying to add a query to main component in order to have "current user" data available in all routes, even in those, where I normally don't have query (static pages). However, these queries doesn't get combined.

### Routes example
```
<Router
	history={browserHistory}
	environment={Relay.Store}
	render={applyRouterMiddleware(ReactRouterRelay)}
>
    // This should always be an active route but this 
    // query doesn't get combined with sub-route queries
	<Route
		name="root"
		path="/"
		component={App}
		queries={ViewerQueries} 
	>
		<Route
			name="post-list"
            path="/posts"
			component={PostList}
			queries={ViewerQueries}
		/>
		<Route
			name="single-post"
			path="/post/:nodeId"
			component={SinglePost}
			queries={NodeQueries}
		/>
	</Route>
</Router>
```

### Relay container on main component (wraps whole app)

This query's supposed to be there for every single page in order to get "current user" data in every page. 

> react-router-relay will automatically generate a combined Relay query config with all queries and parameters from the active React Router routes

I was expecting the following two queries to be combined but they don't. Relay makes 2 separate queries instead.

I thought about using `getFragment()` but the problem is that this component wraps everything. I have no idea how to get _unknown, nameless_ fragment and I couldn't find anything proving that it's possible.
```
export default Relay.createContainer(App, {
	fragments: {
		viewer: () => Relay.QL`
			fragment on Viewer {
				me {
					id
					name
                    email
				}
                # This is most likely not possible (a'la props.children behaviour)
                ${UnknownChild.getFragment('unknownChildFragment')}
			}`
	}
})
```

### Relay container on post list
```
export default Relay.createContainer(PostList, {
    initialVariables: {
        count: 10
    },
    fragments: {
        viewer: () => Relay.QL
            `fragment on Viewer {
                posts(first: $count) {
                    edges {
                        node {
                            id
                            title
                            content
                        }
                    }
                }
            }`
    }
})
```

## My question is:

Is it supposed to happen? (not combining queries)

Only alternative I see is to add Relay containers / queries to every single route, _e.g_ static routes gets queries only with "current user" data? In other words: `StaticComp` usually doesn't have Relay container but now:

```
export default Relay.createContainer(StaticComp, {
	fragments: {
		viewer: () => Relay.QL`
			fragment on Viewer {
				me {
					id
					name
                    email
				}
			}`
	}
})
```

**Comment by taion** [comment]
They're combined into a single query config for execution purposes. Each route however only sees its own queries – otherwise what would the route component Relay container even get if you had two queries with the same name? If you need additional data in your route components, you need to compose in the relevant query for the route.

**Comment by MichaelHilus** [comment]
I have posted a similar question on Stackoverflow: [http://stackoverflow.com/questions/43684386/relay-how-to-merge-instead-of-override-queries-in-nested-routes](url).

How would one achieve to get the App component to query always for the logged in user? Could you give some code example on this?
