### ISSUE TITLE
"prepareParams in Relay query config"

### ISSUE THREAD

**Issue by sedubois** [relay-tools/react-router-relay#202]
I don't understand what is referred to in this [README](https://github.com/relay-tools/react-router-relay#additional-parameters): 

> The prepareParams method has the same signature and behavior as prepareParams on a Relay query config, except that it also receives the current router state as an argument.

What's "prepareParams on a Relay query config", could you link to documentation about it? Or do you mean [prepareVariables](https://facebook.github.io/relay/docs/api-reference-relay-container.html#preparevariables)?

Thanks for providing this lib 😊

**Comment by taion** [comment]
https://facebook.github.io/relay/docs/api-reference-relay-route.html#prepareparams-static-property
