### ISSUE TITLE
Changeable arguments on root?

### ISSUE THREAD

**Issue by unirey** [relay-tools/react-router-relay#205]
I need to pass arguments with root `viewer` because if I do it in a subfield (_e.g_ `me`) and add it to `context`, it's not available in other fields. These arguments are basically like global settings in resolvers (locale _etc_).

```js
const ViewerQueries = {
  viewer: () => Relay.QL`query { viewer(locale: en, settings: 'simple') }`
};

// ...

<Route path="/" component={App} queries={ViewerQueries}>

// ...
```

Is there a way to change `viewer` arguments from `App` component?

---

Only alternative I could think of is to nest everything to `me` instead of `viewer` :

```js
{
    viewer {
        me (locale: en, settings: 'simple') {  // treat 'me' as 'viewer'

            // LOTS of fields

        }
    }
}
```

Now the problem is fragments' composition. Relay doesn't seem to have `this.props.children` functionality. I've struggled with this for days and I cannot find a way out of this problem with my current stack (React, GraphQL, Relay, this module) and this seems to be unprecedented online. Please advice.

**Comment by taion** [comment]
Use prepareParams

**Comment by unirey** [comment]
@taion Im sorry but it still remains unclear how to change `viewer` arguments from React components (_e.g_ on button click) **without** changing URL.
