### ISSUE TITLE
Relay Route render function does pass viewer object but not relay object.

### ISSUE THREAD

**Issue by valorize** [relay-tools/react-router-relay#206]
Hi, thanks for this repo. I have a problem with the render function or generally with Route. When I examine the props which get passed into the render function it contains:
`children, location, params, route, routeParams, router, routes, viewer` but no relay prop which I need to call commitUpdate.

Shouldn't the environment / store which gets passed into Router::environment also passed down to the rendered components?

**Comment by taion** [comment]
That's consistent with what `Relay.Renderer` does. You can close over your Relay environment in some other way.

**Comment by valorize** [comment]
But it is not consistent with Relay.RootContainer renderFetched. https://facebook.github.io/relay/docs/guides-root-container.html#renderfetched

**Comment by taion** [comment]
What do you mean? That's not passing in the Relay object – only an opaque `data`.

**Comment by valorize** [comment]
The data object includes:
a store or viewer object however you name your fragment
a relay object which includes a commitUpdate function.

**Comment by valorize** [comment]
Or maybe I'm wrong. I'll check.

**Comment by taion** [comment]
No, it doesn't. Your component receives the `relay` prop from the Relay container HOC.

**Comment by valorize** [comment]
You're right. A thing I noticed is that my subroutes render function is not called. Is this intentional?

```
<RelayRoute
		path="/" component={App} queries={queries}
		render={({ props }) => props ? logComponent('App', <App {...props} relay={state.environment} />) : <div>Loading...</div>} >
...
		<RelayRoute path="/register" component={RegisterUser}
					render={({ props }) => props ? <RegisterUser {...props} relay={state.environment} /> : <div>Loading...</div>} />
</RelayRoute>
```

My RegisterUser is a normal Component which does not need any data only the environment to save the new data. Therefore I wanted to pass in the relay environment.

**Comment by valorize** [comment]
Furthermore I have route like:
```
<RelayRoute path="/questions/add" component={CreateQuestion} questies={queries} onEnter={requireAuth} />
```
Which is wrapped in an Relay Container HOC and it does not get a relay prop. How should my Relay Container Component know which environment to use anyway?

**Comment by valorize** [comment]
Forget what I wrote. A sleepover showed me my mistake of misspelling queries in the above route.
