### ISSUE TITLE
Multiple Queries

### ISSUE THREAD

**Issue by maletor** [relay-tools/react-router-relay#207]
I'm trying to get a Viewer and a Widget on a page because I have a mutation and I need the viewer's id.

My routes:

```javascript
<Route
  path="widges/:id"
  component={Widget}
  queries={ViewerQueries, NodeQueries}
/>
```

My queries:

```javascript
import Relay from "react-relay";

export default {
  node: () => Relay.QL`
    query {
      node(id: $id)
    }
  `,
};
```

```javascript
import Relay from "react-relay";

export default {
  viewer: () => Relay.QL`
    query {
      viewer
    }
  `,
};
```

My component:

```javascript
export default Relay.createContainer(Widget, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        id
      }
    `,
    node: () => Relay.QL`
      fragment on Widget {
        id
        name
      }
    `,
  },
});
```

I can't seem to get both props to populate.

**Comment by taion** [comment]
You just need to fix the syntax error in your code

**Comment by maletor** [comment]
Sorry, can you be more specific? It's entirely likely it was an issue with copying and pasting to Github?

**Comment by maletor** [comment]
@taion, I only found that code through [this comment](https://github.com/relay-tools/react-router-relay/issues/155#issuecomment-217685290).

**Comment by maletor** [comment]
Ugh, nevermind I figured it out. Every project will have at most three queries. Node, Viewer and NODE + VIEWER.

This pattern of defining queries like this is not idea.

I will hold my breathe for Relay 2.
