### ISSUE TITLE
Support Isomorphic in This Library out of the box.

### ISSUE THREAD

**Issue by SunnyGurnani** [relay-tools/react-router-relay#209]
react-router supports isomorphic by default.

Please support Isomorphic in this library by default so developers dont have to deal with yet another library with mismatching versions of (react-router / react-router-relay / isomorphic-relay-router)

**Comment by taion** [comment]
I'm not going to do that. Relay doesn't support universal apps out-of-the-box, so it wouldn't make sense to do so here either.
