### ISSUE TITLE
React router style URL parameters

### ISSUE THREAD

**Issue by davidye** [relay-tools/react-router-relay#21]
React router supports the definition of parameters directly in the path, as per the react-router docs:

// from the path `/inbox/messages/:id`
var id = this.props.params.id;

Would be nice to be able to pass in queryParams={['id']} and have this work.

**Comment by taion** [comment]
What do you mean? This should already work. `queryParams` is to assert which fields in the query string (`?foo=bar`) to treat as params for the given route.

**Comment by davidye** [comment]
Oh I see, I declared queryParams={['appId']} and that caused errors. Removing that from my router made it work.

**Comment by taion** [comment]
Nope - maybe we can improve the documentation to be a bit clearer, but that's just for working with the query string.
