### ISSUE TITLE
Transpiled version does not work well with Webpack 2

### ISSUE THREAD

**Issue by lemonmade** [relay-tools/react-router-relay#210]
The current version of this library, when transpiled, creates the following entry file:

```js
exports.default = { /* ... */ };
module.exports = exports['default'];
```

That actually looks kind of nonsensical to me, but that's besides the point. This looks like a transpiled default export, but because it is missing the `__esModule` property, doesn't behave as one when using Babel/ Webpack 2:

```js
import useRelay from 'react-router-relay';

render(<Router render={applyRouterMiddleware(useRelay)} />);
```

The above errors out with the following error message:

> [react-router] The middleware specified at index 0 does not appear to be a valid React Router middleware.

Inspecting the import shows that the import is actually just the `module.exports` object; that is, the `default` key has the intended default export. The fix is easy enough but also probably not intended:

```js
import useRelay from 'react-router-relay';

render(<Router render={applyRouterMiddleware(useRelay.default)} />);
```

**Comment by taion** [comment]
dupe https://github.com/relay-tools/react-router-relay/issues/192
