### ISSUE TITLE
query params routing

### ISSUE THREAD

**Issue by andyfen** [relay-tools/react-router-relay#216]
this seems to be proposed in RR4
https://react-router.now.sh/query-params

is there any way to use query params currently ? rather then /:param routing

something like 
https://mysite.com/products?size=medium&color=red

```
initialVariables: {
   color: null,
   size: null
},
// ...
products(first: 100, size: $size, color:$color) {
//...
}
```

Im not sure if there using the router but i saw a really good example of query param routing with relay https://www.verbling.com/find-teachers?language=zh&price%5B%5D=5&price%5B%5D=80&sort=popular

**Comment by taion** [comment]
this library only handles data fetching, not routing
