### ISSUE TITLE
Fetch completes but doesn't cause a refresh when navigating through link (fine during refresh)

### ISSUE THREAD

**Issue by nuclearspike** [relay-tools/react-router-relay#217]
I have two pages, one works properly every time, the other only does if you refresh.

I'm using JS route definitions, the one that does not work every time:

```
import React from 'react';
import Relay from 'react-relay';
import ContractDetail from './components/ContractDetail'

const Queries = {
  contract: () => Relay.QL`query { contract(address: $address) }`
}

export default {
  path: 'contract/:address',
  queries:  Queries,
  component : ContractDetail
}
```

The container for component (ContractDetail.jsx):
```
export default Relay.createContainer(
  ContractDetailDisplay,
  {
    fragments: {
      contract: ()=> Relay.QL`
        fragment on Contract {
          id
          title
          description
          website
        }
      `
    }
  }
)
```

The other component (UserProfile) is very similar... it is a detail view using the param from the url as part of the route's query and a simple fragment of stuff to display.

In a list view, when I click on a contract link, it will not properly display the fetched data. I can see in the network tab that the query is made and the results are returned but it doesn't display them. If I refresh the page, everything displays properly.

Oddly, the UserProfile component works every time, no need to refresh the page. The only real difference between the two pages is that UserProfile was a function component and the other was a stateful class component, but I even tried it as a simple function component.

I'm not quite sure what else could be causing the page to not display properly. I'm using browserHistory if that makes a difference to this. If the data had already been fetched by doing a refresh on the page, then you nav around and come back to that page through a link, the data is there.

I'm very new to Relay, so it's possible it's something very simple and unrelated to this project.

**Comment by taion** [comment]
You probably have a container (maybe Redux) that has `shouldComponentUpdate` and is blocking re-rendering.

**Comment by nuclearspike** [comment]
Thanks for the speedy response! Of the two components, the UserProfile (the one that works) is the only one that has a redux container.

One other thing that is different between the two, is that the Contracts are listed as search results on a page where I'm clicking from. I don't yet quite know how Relay's cache works or how smart it is about what it tries to refresh to fill in the missing details. But, even still, the search results have properties that should be in that cache, I would think.

I have the ContractDetail output the contract prop on render and when I click into it from the listing, I only get this, where it is an object, it just is missing all the data:
{__dataID__: "Q29udHJhY3QtMw=="}

When I do a page refresh, it outputs:
```
{__dataID__: "Q29udHJhY3QtMw=="
description:null
id:"Q29udHJhY3QtMw=="
title:"Contract Title"
website:null}
```

So, I too was wondering if it was a shouldComponentUpdate issue since it seems like it's confused about the fact that the contract prop existed but was unpopulated.

But, one would think if it were merely a case of it not re-rendering but where the data is actually in the Relay cache, then clicking on something else and coming back to the page, it should be able to populate from the cache... but it doesn't.

**Comment by nuclearspike** [comment]
I made some changes to the Graph definitions in Ruby, did some schema refreshes and it is now working... I'm not entirely sure what I did to fix it but the issue is gone. This can be closed.

**Comment by vadimshvetsov** [comment]
I have the same issue, still seeking for the solution. When I switching between sibling pages (both have path `/tag/:id`) child Posts component doesn't rerendered. But when I click Link from main page with path `/` it render correctly. How to get rerendered Posts component inside Tag component when I'm on another Tag component with pressing Link to another `/tag/:id`?
