### ISSUE TITLE
How do I access the relay environment?

### ISSUE THREAD

**Issue by brandonmp** [relay-tools/react-router-relay#219]
I'm trying to implement the lower-level [GraphQLMutation](https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html#content) API in prep for relay 2.0

The constructor requires the `relay environment`

i figured `props.relay` would do the trick, but it throws an error when trying to access `.getStoreData()`

would like to avoid creating a new `environment` for every mutation--is there a way to access this from the props injected by the `router`?

**Comment by taion** [comment]
Relay puts it on context.
