### ISSUE TITLE
How to handle "Object not found" cases?

### ISSUE THREAD

**Issue by mandx** [relay-tools/react-router-relay#223]
I have this Relay app, of course using `react-router-relay`. I have a `render` callback on most of my routes, and I'm using the callback to display Error/Loading screens instead of the actual component, in case there's an error or the data has not arrived yet.

This works fine, but there's one more case to handle: For `node` queries, I can't see how to split when the node is found, or when the node is `null`. No mater what the server returned, I always get something in `props.node`, and the contents is more or less the same in any case. But when my component is being rendered, its `props.node` is correctly set, null for when the server returned nothing, an object when the server returned the found node.

How can I distinguish between "found" and "not found" nodes in the `render` callback?

**Comment by taion** [comment]
I think you need to actually use the lower-level Relay APIs to read into the Relay cache, and see if the object is present. The wrapped opaque Relay nodes you get there can't tell you that.
