### ISSUE TITLE
Module not found: 'react-router/lib/getRouteParams'

### ISSUE THREAD

**Issue by therise3107** [relay-tools/react-router-relay#224]
reacter-router-relay breaks with latest 4.0 version of the react-router.

`Error in ./~/react-router-relay/lib/utils/mergeRouteParams.js
Module not found: 'react-router/lib/getRouteParams' in .../node_modules/react-router-relay/lib/utils

 @ ./~/react-router-relay/lib/utils/mergeRouteParams.js 11:22-64`

**Comment by taion** [comment]
see https://github.com/relay-tools/react-router-relay/issues/193
