### ISSUE TITLE
Named components readyState change at same time even if queries not finished together

### ISSUE THREAD

**Issue by svrcekmichal** [relay-tools/react-router-relay#225]
Hi, I've got following setup of routes config
```
<IndexRoute
  components={{
    top: MeetingVotingPage,
    bottom: MeetingMyVotesPage
  }}
  queries={{
    top: queries,
    bottom: queries
  }}
  render={{
    top: renderMeetingVotingPage,
    bottom: renderMeetingMyVotesPage
  }}
/>
```
and following implementation of renderMethods on both components
```
export const renderMeetingVotingPage = ({...all ,element, done, error, props}) => {
  console.log('MeetingVoting', all);
  if(!done && !error) {
    return (
      <MeetingVotingBlock>
        <LoadingMeetingBuffer />
      </MeetingVotingBlock>
    )
  }
  return React.cloneElement(element, props);
};
```

Even if queries finished few seconds apart, the readyState change will happen at same time when slower is finished. Is it expected behaviour? Because the reason why I've been splitting it to named components is that one of the components is separate from another.

**Comment by svrcekmichal** [comment]
Even if this was expected behaviour, is it possible to somehow change it? If not, I will just send PR and add this to docs.

**Comment by taion** [comment]
It's not intentional per se but it's unavoidable. In practice it shouldn't matter, though, because with a batching network layer it's not really possible for one query to finish earlier.
