### ISSUE TITLE
Go to url based on data recieved from Relay?

### ISSUE THREAD

**Issue by BlakeBrown** [relay-tools/react-router-relay#227]
I have a question! I can see how you can write a route like:

```
<IndexRoute
          component={WidgetList}
          queries={ViewerQueries}
          prepareParams={prepareWidgetListParams}
        />
```

which builds the WidgetList component based off the results of ViewerQueries. I have an alternative use case, I'd like to generate the route itself (not WidgetList!) based off results of ViewerQueries. 

Ex. My server is generating a unique ID and returning it, so I'd like to go to /random-hash based on what's returned from server.

**Comment by taion** [comment]
just do like `router.replace` in your component
