### ISSUE TITLE
Use with react-router 4.0.0

### ISSUE THREAD

**Issue by peterwillis** [relay-tools/react-router-relay#228]
```
ERROR in ../~/react-router-relay/es/utils/mergeRouteParams.js
Module not found: Error: Can't resolve 'react-router/lib/getRouteParams' in '/node_modules/react-router-relay/es/utils'
 @ ../~/react-router-relay/es/utils/mergeRouteParams.js 12:22-64
 @ ../~/react-router-relay/es/RouteContainer.js
 @ ../~/react-router-relay/es/index.js
 @ ./components/Main.js
 @ ./components/app.js
```
Is there someway I can help to make this great library work with react-router 4.0.0? It seems that react-router/lib/getRouteParams does not exist in that version.

**Comment by anishigouri** [comment]
Did you solve this problem?

**Comment by peterwillis** [comment]
Basically you don't need this library if you use react router 4.0

**Comment by taion** [comment]
The issue is that React Router v4 is architecturally incompatible with efficiently fetching data for nested routes with Relay (either classic or modern).

If you're using Relay, you should not use React Router v4.

**Comment by SwarajG** [comment]
With which version we should go with of React Router?

**Comment by taion** [comment]
https://github.com/relay-tools/react-router-relay/blob/fee7b5e9666d46f2a2703914df0a6a872e19063b/package.json#L47
