### ISSUE TITLE
React 16 Compatability

### ISSUE THREAD

**Issue by dbslone** [relay-tools/react-router-relay#242]
With React 16 nearing a release in the near future, is there an upgrade plan for react-router-relay to support React 16? 

I know currently the package can only support up to react-router v3 which has a peer dependency lock at React 15, luckily this package is using the separated prop-types package from React so it should be compatible with 16. From the issues I understand that react-router-relay has no plans to support react-router v4.

Will react-router-relay continue with active development or is the project going to die?

**Comment by taion** [comment]
Well, does it not work right now? If RRv3 isn't getting upgraded to work with React 16, then I'm not going to do anything here.

**Comment by williammustaffa** [comment]
Is this going to be upgraded to work with React 16(already launched)?
