### ISSUE TITLE
Back via Browser History with state persisting?

### ISSUE THREAD

**Issue by vadimshvetsov** [relay-tools/react-router-relay#244]
Is it possible to persist page number in pagination when we click back in Relay Classic?

**Comment by taion** [comment]
Well, the Relay store caches the data that it does. Otherwise if it's in-memory state, you'd need to either use `location.state` or some other state store.

**Comment by vadimshvetsov** [comment]
@taion Thanks. Is `location.state` working when we press back? I can't reproduce this behaviour. Is it possible to cache pagination state for a collection?

**Comment by taion** [comment]
Well you need to keep updating location state as you go...
