### ISSUE TITLE
Router params and fragments example needed in README

### ISSUE THREAD

**Issue by sgwilym** [relay-tools/react-router-relay#26]
The README skims very quickly over working with `react-router`’s params and queries. I'm trying to do something everyone seems to have bumped into, which is to pass on some slugs from the route params to a container (as we're all working around this `viewer` root field for now). I've not had any luck combining #16 and facebook/relay#99.

It would be great if the README could include an example of this with all of the required pieces: route, query and container.

**Comment by sgwilym** [comment]
Update: I've figured this out and will make a PR expanding on this topic in the README soon :)

**Comment by taion** [comment]
Resolved by #29.
