### ISSUE TITLE
Problems with Relay 0.2.1

### ISSUE THREAD

**Issue by sgwilym** [relay-tools/react-router-relay#32]
Just updated to Relay 0.2.1 and trying to view any of my routes now gives me the following:

```
Invalid prop `Component` supplied to `RelayRootContainer`, expected a RelayContainer. Check the render method of `ReactRouterRelay.RootComponent`.
```
and 
```
Uncaught TypeError: Component.hasFragment is not a function
```

Seems like Relay isn’t happy about what react-router-relay is passing along. Anyone having the same problem?

**Comment by sgwilym** [comment]
Apologies, just saw this is being discussed in #31

**Comment by taion** [comment]
I'll cut 0.4.3 after we merge https://github.com/relay-tools/react-router-relay/pull/33.
