### ISSUE TITLE
Container.hasVariable

### ISSUE THREAD

**Issue by devknoll** [relay-tools/react-router-relay#37]
react-relay@master adds `hasVariable` to the list of methods required for `RouteAggregator`

cc @taion

**Comment by taion** [comment]
Would you mind adding that to https://github.com/facebook/relay/blob/master/src/container/isRelayContainer.js as well, so the error message will be less cryptic?

**Comment by taion** [comment]
Oh, you're way ahead of me: https://github.com/facebook/relay/commit/6cc8f96cdb7dcebebb38f30b7d64b08dfd83fb18#commitcomment-13137179
