### ISSUE TITLE
willTransitionTo not working

### ISSUE THREAD

**Issue by almasakchabayev** [relay-tools/react-router-relay#41]
What is the equivalent of willTransitionTo in react-router-relay? I want to do something like:
    static willTransitionTo(transition) {
      if (!LoginStore.isLoggedIn()) {
        transition.redirect('/login', {}, {'nextPath' : transition.path});
      }
    }

Thx

**Comment by taion** [comment]
This has nothing to do with this package. It's `onEnter` on the routes in the new React Router versions.

**Comment by almasakchabayev** [comment]
I'm sorry for noob questions, but I get another error: I tried 
```
function requireAuth(nextState, redirectTo) {
  if (!LoginStore.isLoggedIn())
    redirectTo('/login', null, { nextPathname: nextState.location.pathname });
}
export default (
  <Route path="/" component={App}>
    <Route path='signup' component={Signup} />
    <Route path='login' component={Login} />
    <Route path='dummy' component={Dummy} queries={DummyQueries} onEnter={requireAuth}/>
  </Route>
);
```

but I get redirectTo is not a function

**Comment by taion** [comment]
You can find the React Router 1.0.0-beta3 docs here: http://rackt.github.io/react-router/tags/v1.0.0-beta3.html
