### ISSUE TITLE
Creating an "Instantfetch" React Router Link component

### ISSUE THREAD

**Issue by KyleAMathews** [relay-tools/react-router-relay#44]
@devknoll came up with what I think is a really cool idea on Slack the other day. I'll paste it in here as it's about to be eaten and dissolved forever by the dread Slack time monster.

kylemathews [3:57 PM] 
I don’t like 500ms delays so I’d vote for pulling the detailed view fragment into the list view query to avoid that :simple_smile:

gmonaco [3:57 PM] 
that gives me an idea: declarative http://instantclick.io for relay

kylemathews [3:58 PM] 
@gmonaco: oooo nice! That’d be really cool!

gmonaco [3:58 PM] 
^ declarative too! :wink:

gmonaco [3:58 PM]
clicking this will take you to this route, here are the data requirements that route needs = done

kylemathews [3:59 PM] 
yeah, just wrap React-Router’s ​`Link`​ component

...

kylemathews [4:00 PM] 
actually, I’d use a instantfetch Link everywhere

kylemathews [4:00 PM]
why not really

gmonaco [4:02 PM] 
couple it with some machine learning to see if they’re likely to actually click it, right?

gmonaco [4:02 PM]
…right? :wink:

kylemathews [4:03 PM] 
I think what instantclick is solid—measure how long they hover over a link e.g. past 200ms start fetching that route’s data (edited)

kylemathews [4:04 PM]
doesn’t Relay detect if a particular query is already in-flight and not send another one? Otherwise we’d need to prevent that.

gmonaco [4:05 PM] 
it does in theory, but I think there might still be a bug with that

My question now is how to actually implement this? My thought is that the `InstantLink` component would detect mouseovers and once ~200miliseconds has gone by, trigger a fetch for that route's data. The component part is easy but I haven't figured out how to do the manual fetch. I did a quick look through the code here but wasn't able to figure out if there's a clear way to say "give me all Relay queries for this ReactRouter route".

Any thoughts @devknoll and @taion?

**Comment by KyleAMathews** [comment]
Also, @devknoll it'd be good to know if there is a bug for Relay not correctly detecting an in-flight query.

**Comment by taion** [comment]
Does this necessarily have to be a react-router-relay thing, though? Presumably a more generic solution is possible for any React Router based site (i.e. render the new whatever into an off-document `div` or something to handle all the data fetching).

I guess with Relay you have the concept of queries, but it'd be nice if we could find a generic solution that weren't restricted to just this one set of integrations.

**Comment by KyleAMathews** [comment]
Oh interesting. I hadn't thought about making it generic. That would be really nice and work for more purposes other than just data fetching e.g. loading js chunks for new routes.

Is this possible thought? I don't know React Router well enough to know you can load loading multiple routes at the same time.

**Comment by devknoll** [comment]
@KyleAMathews I was specifically referring to https://github.com/facebook/relay/issues/140

**Comment by taion** [comment]
@KyleAMathews 

The idea would be that you just load up the next location in an unmounted `<div>` somewhere, e.g. completely duplicate everything (but invisibly).

**Comment by taion** [comment]
I really feel like this would be best handled upstream in a more generic way in React Router. Most of the work here would be matching the route from link, then going from there. Please re-open this issue in some form on the React Router repo - it'd at least give us a better way to move forward on this, because I don't think I can handle this purely in `react-router-relay`.
