### ISSUE TITLE
Caveats

### ISSUE THREAD

**Issue by halt-hammerzeit** [relay-tools/react-router-relay#46]
```Relay containers attempt to avoid re-rendering except when necessary. However, they can only do so when all props not through Relay are of scalar types. As the props injected by Relay Router into route components are not of static types, this optimization does not work there. As such, when using React Router with Relay, you should attempt to make the render method on any route components as lightweight as possible, and leave the real rendering work to child components that only receive scalar non-Relay props.```

I don't understand what are you saying in the Caveats section.
Can you provide an example there?

**Comment by taion** [comment]
It's more of a micro-optimization around pure-render-style not-re-rendering. I wouldn't worry about it too much - it's not a particularly big deal and likely not something you need to worry about.

**Comment by taion** [comment]
I re-wrote that section a bit. Also, http://facebook.github.io/relay/docs/thinking-in-graphql.html#achieving-view-consistency explains what's going on in a bit more detail.
