### ISSUE TITLE
query is not a function in RouteAggregator

### ISSUE THREAD

**Issue by Aweary** [relay-tools/react-router-relay#54]
I've been getting this `query is not a function` error, which I've captured below. I added a log in the `Object.keys(queries).forEach` call and also logged out `queries` before that.

<img width="865" alt="screen shot 2015-09-28 at 11 21 32 am" src="https://cloud.githubusercontent.com/assets/6886061/10141612/1df8cdec-65d3-11e5-926f-3ebea7c29032.png">

[This call](https://github.com/relay-tools/react-router-relay/blob/57349cbf53c93ed04ea6896bce3a88d2af472724/src/RouteAggregator.js#L58) seems to assume `query` is a function without checking so, which is causing the error. Below is my setup. Note that I've also tried exporting a simple object from `viewerQueries` like is done in the todoMVC example, and its the same issue.

_app.js_
```js
import Application from './components/App';
import Property from './components/Property';
import Relay from 'react-relay';
import ReactDOM from 'react-dom';
import {Router, Route} from 'react-router';
import ReactRouterRelay from 'react-router-relay';
import ViewerQueries from './queries/ViewerQueries';


Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://localhost:3000/')
);

ReactDOM.render(
  <Router createElement={ReactRouterRelay.createElement}>
    <Route
      path="/" component={Application}
      queries={new ViewerQueries()}>
      <Route path='properties' component={Property} queries={new ViewerQueries()}/>
    </Route>
  </Router>,
  document.getElementById('root')
);
```

_queries/ViewerQueries.js_

```js
import Relay from 'react-relay';

class ViewerQuery extends Relay.Route {
  static queries = {
    viewer: () => Relay.QL`
    query { viewer }`
  };
  static routeName = 'ViewerQuery'
}

export default ViewerQuery;


```

**Comment by taion** [comment]
Per the basic usage example: https://github.com/relay-tools/react-router-relay#usage, queries are expected to be actually just the queries, and not the Relay route.

**Comment by Aweary** [comment]
As I said in the OP the issue occurs either way

**Comment by taion** [comment]
Relay actually explicitly expects that all queries be functions. Does the TodoMVC example not work for you? `queries` just needs to be an object with the query functions as values.

**Comment by Aweary** [comment]
Ignore that, looks like it was an issue related to the build process. :+1:

**Comment by Aweary** [comment]
@taion on the topic, is there any plan or considerations for adding support for `Relay.Route` instances? I do wish I could add least add static properties like `routeName` to be used instead of the generated value(s)

**Comment by taion** [comment]
No; it was initially there but @cpojer suggested it was better not to support that.

Note that in practice with the new query shorthand, you're probably going to just end up using the same `viewer` query everywhere anyway, which points more in going in an opposite direction.

**Comment by devknoll** [comment]
I think route names are going away in the future too.
