### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by madeuz** [relay-tools/react-router-relay#69]
Currently every Relay Container rendered on server side appears as `<noscript>` tag. This happens because child elements returned from [Container](https://github.com/relay-tools/react-router-relay/blob/master/src/Container.js#L74) are always `null` and causing error `TypeError: Cannot read property 'firstChild' of undefined` ([sample repo here](https://github.com/facebook/relay/issues/136#issuecomment-145803717)). Please provide a way to delay fetching data as described in [#36 (comment)](https://github.com/facebook/relay/issues/36#issuecomment-130402024). I know that [RelayStore.primeCache](https://github.com/facebook/relay/blob/2a86be3e71cdc6511fa994e3de539f72070da1b4/src/store/RelayStore.js#L85-L90) that is [called by the internals of RelayRootContainer](https://github.com/facebook/relay/blob/2a86be3e71cdc6511fa994e3de539f72070da1b4/src/container/RelayRootContainer.js#L193) currently doesn't accept this but that can be easly fixed even locally.

**Comment by taion** [comment]
This request doesn't make any sense until Relay itself supports server-side rendering.

**Comment by moret** [comment]
@madeuz if you're still interested, check out https://github.com/denvned/isomorphic-relay-router

**Comment by rattrayalex** [comment]
Relay itself now supports server-side rendering. Changing `RouterContext` to `RelayRouterContext` broke my app with the error mentioned above. 

Can this be re-opened?

**Comment by taion** [comment]
Where are you seeing server-side rendering support for Relay?

**Comment by rattrayalex** [comment]
https://github.com/facebook/relay/issues/558 and https://github.com/facebook/relay/issues/136 track this. But I think you're correct that it's not yet ready. Apologies.

**Comment by taion** [comment]
Right. Take a look at @denvned's repos.
