### ISSUE TITLE
Relay 0.5.0 invariant expects query to be empty, fatals

### ISSUE THREAD

**Issue by LegNeato** [relay-tools/react-router-relay#72]
See https://github.com/facebook/relay/issues/585.

I guess the issue is somewhere around:

https://github.com/relay-tools/react-router-relay/blame/master/src/RouteAggregator.js#L58

**Comment by taion** [comment]
We need to make a bigger update to bring everything up to date. Watch this space.

**Comment by LegNeato** [comment]
:+1:
