### ISSUE TITLE
Diagnosing failure after upgrading to v0.8.0

### ISSUE THREAD

**Issue by colllin** [relay-tools/react-router-relay#76]
Hey, How can I diagnose a silent failure after upgrading both react-router-relay and react-router?

I was already on react-router@1.0.0-rc3, but upgraded to Relay@0.5.0, react-router-relay@0.8.0, and react-router@1.0.0.

I switched to using `<RelayRouter>`, but now one of my routes doesn't correctly render its children.

I have something like...

    ReactDOM.render(
        <RelayRouter
            history={createBrowserHistory()}
        >
            <Route path="/" component={AdminApp}>
                <IndexRoute component={CampaignList} queries={ViewerQueries} />
                <Route path="/campaigns/:campaignId" component={Campaign} queries={CampaignAndViewerQueries}>
                    <IndexRoute component={CampaignMain} queries={CampaignAndViewerQueries} />
                    <Route path="geometries" component={CampaignGeometries} queries={CampaignAndViewerQueries}>
                        <Route path="upload" component={CampaignGeometriesUpload} queries={CampaignQueries} />
                    </Route>
                </Route>
            </Route>
        </RelayRouter>,
        document.getElementById('app-root')
    );

And CampaignList renders correctly at the root (`/`), but at `/campaigns/:id`, Campaign doesn't render.  My best guess is that it has something to do with having deeper nesting?  Since CampaignList doesn't have any child routes but Campaign does.

**Comment by taion** [comment]
You're not getting an error or anything?

**Comment by colllin** [comment]
Nothing :/

**Comment by taion** [comment]
Try setting e.g. a breakpoint in `RelayRoutingContext.render`. Is the route getting properly matched by the router?

**Comment by colllin** [comment]
How can I verify that?  It looks like it's getting a `campaignId` param, so it's at least partly getting getting matched.

I've got a breakpoint in this function:

	  RootComponent.prototype.render = function render() {
	    return _react2['default'].createElement(_reactRelay2['default'].RootContainer, _extends({}, this.props, {
	      Component: this._routeAggregator,
	      renderFailure: this.renderFailure,
	      renderFetched: this.renderFetched,
	      renderLoading: this.renderLoading,
	      route: this._routeAggregator.route
	    }));
	  };

And `this._routeAggregator.route` looks like:

```
{
  "name": "$$_aggregated-$$_route[2]_campaign-$$_route[2]_viewer-$$_route[3]_campaign-$$_route[3]_viewer",
  "queries": {
    
  },
  "params": {
    "campaignId": "Q2FtcGFpZ246MA=="
  }
}
```

**Comment by taion** [comment]
Check the array of components. Also, what does the React devtool show as actually being rendered?

**Comment by pasviegas** [comment]
Also having problems after upgrading to 0.8 :(

There is nothing in the console and React devtools renders 'null' inside StaticContainer.

**Comment by taion** [comment]
Try setting a breakpoint in `RouteContainer` and see why `getData` is not returning.

**Comment by colllin** [comment]
@taion The React devtool shows this:
![image](https://cloud.githubusercontent.com/assets/185923/11194915/28c00122-8c6c-11e5-9046-77a9bc39c80f.png)

It shows the CampaignList component when it should be Campaign.

Trying to find the array of components and getData now...

**Comment by colllin** [comment]
New information:

I was initially upgrading from:

    "react-relay": "^0.3.2",
    "react-router": "^1.0.0",
    "react-router-relay": "^0.6.2",

to:

    "react-relay": "^0.5.0",
    "react-router": "^1.0.0",
    "react-router-relay": "^0.8.0",

As an experiment, I tried upgrading to an intermediate step:

    "react-relay": "^0.4.0",
    "react-router": "^1.0.0",
    "react-router-relay": "^0.7.0",

And I found the same bug there.  Since I don't see any code changes between v0.6.2 and v0.7.0, it must be a bug in react-relay, right?

**Comment by colllin** [comment]
Ok, I was able to get it working with `react-relay@0.4.0` and `react-router-relay@0.7.0` by upgrading to `babel-relay-plugin@0.3.0`.

Unfortunately, I'm still stuck on getting `relay@0.5.0` and `react-router-relay@0.8.0` to work, even on the latest `babel-relay-plugin@0.4.1`.

**Comment by taion** [comment]
Do you have a runnable example?

**Comment by colllin** [comment]
I made one.  It seems to be related to switching queries between routes:

https://github.com/tomnod/react-router-relay-issue-76

**Comment by Agrosis** [comment]
I tried out your code, it seems that `CampaignQueries` is broke, If you take out the $campaignId parameter, it should work fine. The correct signature for the query function should be `Component` and then `param`. But if you try to stick any arguments in the function the whole thing breaks.

**Comment by taion** [comment]
Yup, per @Agrosis, you have the wrong signature for `CampaignQueries`. It should be either:

```js
    campaign: () => Relay.QL`
        query {
            campaign(id: $campaignId)
        }
    `,
```

or

```js
    campaign: (Component, params) => Relay.QL`
        query {
            campaign(id: $campaignId) {
                ${Component.getFragment('campaign', params)}
            }
        }
    `,
```

I had been doing something incorrect with ignoring the signature of the query function. It's not correct to specify a query function with arguments if you're not going to manually compose in the fragment.

**Comment by colllin** [comment]
Totally fixed it.  Thanks for your help @taion and @Agrosis .  How do you feel about adding an error so that other people who make the same issue have an easier time figuring it out?  I can implement if you can direct.

Also, how/where did you learn this?

> It's not correct to specify a query function with arguments if you're not going to manually compose in the fragment.

**Comment by taion** [comment]
I can't - or rather it doesn't really make sense at that level for me to introspect into your query to figure out what it's doing. I'm giving you exactly what you'd get if you passed this query directly into upstream Relay, where it would also break in a similar way.

This is really just the syntax for writing Relay queries - you probably don't want to use the old syntax any more, but it used to be the only syntax before @devknoll added the shorthand.

**Comment by devknoll** [comment]
Yeah, I don't think it was specifically mentioned anywhere, but it's been the documented way since relay@0.2.1. I think since that so closely followed release, it wasn't expected to affect a large number of people.

It looks like https://github.com/facebook/relay/commit/658587eb5035c09d01c90116e7abeda43e7cd34a is relaxing the restriction here, which may make this even more confusing :wink:

**Comment by taion** [comment]
So for reference, this is the query:

```js
    campaign: (campaignId) => Relay.QL`
        query {
            campaign(id: $campaignId)
        }
    `,
```

I don't believe this is valid under any version of Relay.

Previously we were being sloppy and just dropped all of the arguments entirely, which led to https://github.com/relay-tools/react-router-relay/issues/72 and https://github.com/facebook/relay/issues/585, which I fixed in https://github.com/relay-tools/react-router-relay/commit/c1092ed3dab1ce1ff339c93439e9507fc6f465d1.

**Comment by devknoll** [comment]
Got it.
