### ISSUE TITLE
Allow passing in the Router component.

### ISSUE THREAD

**Issue by Agrosis** [relay-tools/react-router-relay#77]
Could there maybe be a prop to `RelayRouter` that lets us pass down the Router component that should be rendered? If it isn't specified, could probably default to the react-router Router. This would be useful so we could use things like ReduxRouter or other custom routers.

If you approve, I'd like to make a PR for this. :)

**Comment by taion** [comment]
You should be passing `RelayRoutingContext` into the Redux router, not the other way around.

**Comment by Agrosis** [comment]
Ahh, ok `RelayRouter` just passes in the context to the default router, got it. Thanks :)

**Comment by taion** [comment]
Yup. Exactly.

**Comment by bsr203** [comment]
can you please explain how it changed in latest version as I could make it work with `"react-router-relay": "^0.7.0",`

```
import {render} from 'react-dom';
import {ReduxRouter} from 'redux-router';
import ReactRouterRelay from 'react-router-relay';
...
    const store = createStore();
...
  const component = (
      <Provider store={store}>
        <ReduxRouter
          createElement={ReactRouterRelay.createElement}
        />
      </Provider>
    );
    const container = document.getElementById('app');
     render(component, container);
```
and the routes are configured with the store
```
reduxReactRouter({
      routes,
      createHistory,
    }),
```
and how does it change now. Tried like,

```
import {ReduxRouter} from 'redux-router';
import {RelayRoutingContext} from 'react-router-relay';

...
    const component = (
      <Provider store={store}>
        <ReduxRouter {...RelayRoutingContext} />
      </Provider>
    );
```
rest same. But getting error

```
Warning: Failed Context Types: Required context `route` was not specified in `Relay(Connect(Dashboard))`. Check the render method of `RoutingContext`.
```

**Comment by bsr203** [comment]
@taion it might be an issue with reduc-router then https://github.com/vslinko-forks/redux-router/commit/a6f378e0400a3b95fe51ee478d8e8d04443fdbc2

**Comment by taion** [comment]
Right, redux-router would have to allow something like that.
