### ISSUE TITLE
Children routes not rendered after updating to 0.8.0

### ISSUE THREAD

**Issue by xuorig** [relay-tools/react-router-relay#82]
First heres what I'm running:
```
    "react": "0.14.3",
    "react-dom": "^0.14.3",
    "react-relay": "0.5.0",
    "react-router": "1.0.0",
    "react-router-relay": "0.8.0",
```

My routes
```
ReactDOM.render(
  <RelayRouter history={createBrowserHistory()} routes={routes} />,
  document.getElementById('root')
);
```

```
export default (
  <Route
    path="/"
    component={App}
    queries={ViewerQueries}
  >
    <IndexRoute
      component={InsyteList}
      queries={ViewerQueries}
    />
    <Route
      path="insyte/:id" component={Insyte}
      queries={InsyteQueries}
    />
  </Route>
)
```

The IndexRoute is always the one that renders even when hitting urls like `#/insyte/123`.
Actually any route will always render the index route even if I type something like `/#/aadfasdfsdasdf`
When I inspect route aggregator i see this for the `route`:
```
route: Object
name: "$$_aggregated-$$_route[1]_viewer-$$_route[2]_viewer"
params: Object
__proto__: Object
```

Thought it was related to #76 but my queries seem OK.
You can take a look at the actual code here if it helps: https://github.com/xuorig/insyto/tree/master/js

**Comment by taion** [comment]
If you're using browser history, that's to be expected, no?

**Comment by xuorig** [comment]
:facepalm: thank you :dancer:
