### ISSUE TITLE
URL route param vs descriptive label

### ISSUE THREAD

**Issue by rblakeley** [relay-tools/react-router-relay#83]
Say I have a component `UserPage` whose route takes a `userId` parameter which is a serialized string that is used to fetch the data for a user.
```
/user/:userId
```
But I would like to show a URL with the user's name.
```
/user/rocketman
```

The route would need to be supplied with the `userId` and `userName` params, but only show the `userName` param in the URL bar and only pass the `userId` param to the query.

Are there any APIs for this or thoughts for adding it?

**Comment by taion** [comment]
How were you doing this without Relay?

**Comment by rblakeley** [comment]
@taion I haven't done this before.

Is the prescribed way of having a name in the URL to use the name as the key for querying a user?

Would this question would be more appropriate in the react-router repo?

**Comment by taion** [comment]
In general I think you're asking the wrong question here.

If you can do the name to ID mapping on the client side, you can just use `prepareParams`.

If you can't do the name to ID mapping on the client side, but want names in your URLs, then your server endpoint needs to accept the name and do the conversion.

**Comment by rblakeley** [comment]
@taion thanks, that makes sense.
