### ISSUE TITLE
Does react-router-relay support javascript objects/lists being passed through stateParams/prepareParams?

### ISSUE THREAD

**Issue by gccaldwell99** [relay-tools/react-router-relay#85]
When I switch one of my stateParams from a string to a list/object my route component fails to render, but I don't get a javascript or compiler error. Switching it back to a string fixes the issue.

**Comment by taion** [comment]
They just get passed through as objects to Relay. Same as if you weren't using this lib.

**Comment by kotfalya** [comment]
I reproduced this bug. I found problem [here](https://github.com/relay-tools/react-router-relay/blob/master/src/RouteAggregator.js#L125)  .Js can't compare objects
