### ISSUE TITLE
Route parameters not propagating correctly

### ISSUE THREAD

**Issue by geraldfvds** [relay-tools/react-router-relay#92]
When I try to use a route parameter in the QL for a container, it seems to be doing the wrong thing. I'm not sure if the issue is with this library, so sorry if it's not :)

I have the following:

    var HomeQueries = {
        store: (Component) => Relay.QL`
        query {
          store {
             ${Component.getFragment('store')},
          },
        }
    };
    
    /* ...... */
    
    <RelayRouter>
        <Route name="home" path="/:tenant" component={AppView} queries={HomeQueries}/>
    </RelayRouter>,
    
    /* ....... */
    
    AppView = Relay.createContainer(AppView, {
        initialVariables: {
            tenant: 'hk'
        },

        prepareVariables: (args) => {
            console.log('prep tenant: ' + args.tenant);
            return {
                tenant: args.tenant
            };
        },

        fragments: {
            store: () => Relay.QL`
                fragment on Store {
                    tenant(id: $tenant) {
                        id, name
                    }
                }
            `
        }
    });

When I go to this route: /vds

I see that prepareVariables is firing twice; the first time with tenant='hk', and the second time with tenant='vds'. But only one graphql request is being made, with tenant(id: "hk"). If I set tenant to null in initialVariables, then I just get a 400 error as it tries to make a graphql request with no id. My expectation would be that there would be one graphql call with tenant(id: "vds"). 

Bug or ID-10-T user error?

**Comment by taion** [comment]
You're passing down params wrong. Check the other issues.

**Comment by defrex** [comment]
@geraldfvds did you figure this out? I'm having the same problem, and I'm haven't found an answer in the other issues.

**Comment by geraldfvds** [comment]
@defrex  - I found a way that works, though I'm not sure it's "the" way. But essentially this is what I ended up using for HomeQueries:

```
var HomeQueries = {
    tenant: (Component) => {

        return Relay.QL`
            query {
                tenant(id: $tenantId) {
                    ${Component.getFragment('tenant')}
                }
            }
            `;
    }
};
```
And then my container:

```
AppView = Relay.createContainer(AppView, {

    initialVariables: {
        id: null
    },

    fragments: {
        tenant: () => Relay.QL`
            fragment on Tenant {
                id, name
            }
        `
    }
});
```

Hope this helps.

**Comment by defrex** [comment]
Thanks for getting back to me. I had just figured out a different solution. I'll add it here for the next person that comes along.

When I had the error, I was doing this:

```js
Relay.createContainer(Dashboard, {
  prepareVariables: (variables)=> {
    return { date: `${variables.year}/${variables.month}` };
  },
  fragments: {
    viewer: ()=> Relay.QL`
      fragment on Viewer {
        summary(month: $date) {
          income
          allocated
          spent
          net
        }
      }
    `,
  },
});
```

`prepareVariables` would be called twice, once with `year` and `month` set correctly (they are from the route), and once with them `undefined`. The second call would be used for the query, resulting in "undefined/undefined" as my arg.

I changed it to this:

```js
Relay.createContainer(Dashboard, {
  prepareVariables: (variables)=> {
    if (variables.year && variables.month)
      return { ...variables, date: `${variables.year}/${variables.month}` };
    else
      return variables;
  },
  fragments: {
    viewer: ()=> Relay.QL`
      fragment on Viewer {
        summary(month: $date) {
          income
          allocated
          spent
          net
        }
      }
    `,
  },
});
```

It turns out the second call to `prepareVariables` passes in the returned `variables` from the first call. I guess because I have nested routes with `queries`. That means the problem can be solved by not squashing anything, and not making any assumptions.

**Comment by skosch** [comment]
I am having exactly the same problem as @defrex, but his solution doesn't work for me. How come `prepareVariables` is being called twice, and why is it empty the second time around?

My component is on an `IndexRoute`, nested four levels deep into the router. There are no other Relay containers above it, so I'm not composing fragments anywhere. How can I make sure all route params are passed in correctly?

```jsx
<Router
    history={browserHistory}
    render={applyRouterMiddleware(useRelay)}
    environment={Relay.Store}>
      <Route path="/" component={TabBarLayout} params={{nav: navTabs}}> // not a Relay container
        ...
        <Route path="/:year" >                  // <--- I need the :year
          <IndexRoute component={Overview} />
          ...
          <Route path="emails">
            <IndexRoute  component={EmailsList} queries={ViewerQuery} /> // <--- not working
            ...
          </Route>
          ...
```

used with
```js
fragments: {
    viewer: () => Relay.QL`fragment on Viewer {
      year: yearByYear(year: $year) {   // <--- $year is undefined on second pass 
        emails(first: 100) {
          ...
```

(That being said, everything is working wonderfully otherwise. Thanks a ton for providing this tool @taion!)

**Comment by skosch** [comment]
Aha! The problem goes away as soon as I add an `initialVariables` section. As far as I can tell, the need for this isn't documented in the README file. Could anyone confirm?

**Comment by taion** [comment]
You probably need `initialVariables`, but I don't think that's a react-router-relay thing.

**Comment by skosch** [comment]
Ah, I see. It's challenging keeping track of which ones of the many moving pieces belong to which project. Thanks for the quick response!

**Comment by taion** [comment]
What I mean is – when working with Relay, containers that need variables need to declare them in `initialVariables`, else things won't work.

**Comment by elado** [comment]
Had the same issue.

Due to https://github.com/facebook/relay/issues/112 I had to nest everything under a `viewer` for those >1 arg queries.

What was missing on this thread for me was explicitly passing vars to the fragment. Here's what I did:

```jsx
// routes
<Route path=":productId" queries={ViewerQuery} component={ProductPage} />

// queries
const ViewerQuery = {
  viewer: (Component, vars) => Relay.QL`
    query {
      viewer {
        ${Component.getFragment('viewer', vars)} # <-- this
      }
    }
  `
}

// container
ProductPage = Relay.createContainer(ProductPage, {
  initialVariables: {
    productId: ''
  },

  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        product(id: $productId) {
          id
          name
        }
      }
    `,
  },
})
```

Without explicitly passing `vars`, this is the error I got:

```
Warning: RelayContainer: component `ProductPage` was rendered with variables 
that differ from the variables used to fetch fragment `viewer`. The fragment was 
fetched with variables `{"productId":""}`, but rendered with variables 
`{"productId":"abc"}`. This can indicate one of two possibilities: 
 - The parent set the correct variables in the query - 
 `ProductPage.getFragment('viewer', {...})` - but did not pass the same 
 variables when rendering the component. Be sure to tell the component what 
 variables to use by passing them as props: `<ProductPage ... productId={...} 
 />`.
 - You are intentionally passing fake data to this component, in which case 
 ignore this warning.
```

**Comment by KCraw** [comment]
@elado  Yes, that's the right way to do it anytime a parent component needs to pass down Relay variables to a child component so it has them available when generating its query. You also have to pass the prop itself in the React component, but here `react-router-relay` is handling that for you.
