### ISSUE TITLE
Nested routes and query variables

### ISSUE THREAD

**Issue by ooflorent** [relay-tools/react-router-relay#93]
**NOTE:** This is more a question than an issue but the discussion may lead to a new feature.

---

I am working on a big application (more than 100 routes) with nested routes. I am facing an issue with nested routes and variables. The application is a site manager. The user first selects an available site then he can interact with its configuration.

Routes are nested as below:

```
/             <- Requires site selection
  /overview   <- All child routes assume a site is selected and add fragments to Site node
  /settings
  /stats
```

Having a lot of routes specifying the queries and the variable resolution seems really strange and leads to copy/paste configuration. What is the correct way of doing this? Is it possible to propagate fetched data to child route components?

Since all child routes are included into their parent using `this.props.children`, it seems impossible to query `site` from the root and send it to the child components.

---

**Schema**

```graphql
type RootQuery {
  viewer: Viewer
}

type Viewer {
  sites: SiteConnection
  site(id: ID!): Site
}

type Site implements Node {
  id: ID!
}
```

**Routes**

```js
const ViewerQueries = {
  viewer: () => Relay.QL`query { viewer }`
}

{path: "/", queries: ViewerQueries, component: App, childRoutes: [
  {path: "overview", component: Overview},
  {path: "settings", component: Settings},
  {path: "stats", component: Stats},
]}
```

**App**

It wraps the entire application and provides a dropdown menu to select another site. It defines the following fragment:

```js
{
  viewer: () => Relay.QL`
    fragment on Viewer {
      sites {
        ${SiteSelector.getFragment('sites')}
      }

      site(id: $selectedSite) @include(if: $selectedSite) {
        id
        ${SiteSelector.getFragment('selectedSite')}
      }
    }
  `
}
```

`App` abuses `componentDidMount` and `componentWillReceiveProps` to store the selected site. If none it will select the first edge in `sites`.

---

Given all the above information, how it is possible to the child routes to receive the selected site? As mentioned earlier, since there is a lot of pages, using `prepareParams` and `queries` on each route seems really heavy.

**Comment by taion** [comment]
By design we don't want explicit data passing across routes – otherwise it'd be impossible to determine loading state on a per-route basis.

In your case, I'd pull your `site` field out from under `viewer` and just nest it under your top-level `query`. Then you can share a top-level

```js
const SiteQueries = {
  site: () => Relay.QL`query { site(siteId: $siteId) }`
}
```

where `siteId` comes from your current URL or from `location.state`.

**Comment by ooflorent** [comment]
Thanks @taion for your response. Indeed using `location.state` was the solution.

```js
const relayRoute = {queries: ViewerQueries, onEnter: injectedSelectedSite, stateParams: ["selectedSite"]}
const routes = {...relayRoute, path: "/", component: App, childRoutes: [
  {path: "overview", component: Overview},
  {path: "settings", component: Settings},
  {path: "stats", component: Stats},
]}
```

The following works on `/` but not on child routes. I need to add an `onEnter` hook on each child routes to inject the parameter into the location state. Is there another solution?

**Comment by taion** [comment]
Personally, for this sort of thing, I just put some identifier in the URL. I think it makes more sense navigation-wise too.

You can also use `prepareParams` and read from an external store, though.

**Comment by ooflorent** [comment]
I totally agree with you on putting the identifier in the URL but our product team don't want it. I'll try using `prepareParams`. Many thanks.

**Comment by ianstormtaylor** [comment]
@ooflorent did you ever solve this nicely? 

I have the same issue, it seems fairly common... GitHub's dashboard page at `/` (and `/issues`, `/pulls`) for example would need something like this.

**Comment by ooflorent** [comment]
@ianstormtaylor We tried 3 different approches:

1. Inject parameters into `location.state` and add `stateParams` when we need to read them. I wasn't able to find an elegant way to do this so we tried another thing.

2. Add a route factory to access a redux store and extract what we need.

    ```js
    // `store` is available in this scope
    function relayRoute(route, mapStateToParams) {
      return {...route, prepareParams: () => mapStateToParams(store.getState())}
                        ^^^^^^^^^^^^^                         ^^^^^^^^^^^^^^^^
    }

    const routes = relayRoute(
      {path: "/", queries: SiteQueries, /* ... */}, 
      state => ({siteId: state.selectedSiteId})
    )
    ```

    This approach was definitely the way to go in our case. However we found annoying having to a call `relayRoute` in our chunks because routes are defined in multiple chunks. We had to change our route definitions to pass `relayRoute` to them.

    ```js
    // main chunk
    const routes = {/* ... */, getChildRoutes: (location, cb) => {
      require.ensure([], require => {
        // some other chunk
        cb(require("./some/module/routes")(relayRoute))
                                           ^^^^^^^^^^
      })
    }}
    ```

3. Create a custom `RouterContext` wrapping `RelayRouterContext` to add `connectParams` to the route definitions.

    ```js
    const routes = {/* ... */, connectParams: state => ({siteId: state.selectedSiteId})}
    ```

    This is the solution we chose and are really happy with it.

**Comment by amkoehler** [comment]
@ooflorent not sure if anything has changed with your project since posting this solution, but this appears to be a good solution to a similar problem of mine. Thanks for sharing.
