### ISSUE TITLE
react-router-relay@0.9.0 seems to require react-router@2

### ISSUE THREAD

**Issue by KyleAMathews** [relay-tools/react-router-relay#95]
I was getting "Failed Context Types" errors until I downgrade to 0.8.0. This should either be documented or if 0.9.0 *should* work with react-router@1 then fix whatever is the problem.

**Comment by taion** [comment]
It's marked as such, though: https://github.com/relay-tools/react-router-relay/blob/v0.9.0/package.json#L38

**Comment by KyleAMathews** [comment]
Oh cool, forgot to look there. NPM 3 doesn't do the hard stop on `peerDependencies` any more so it wasn't obvious what was wrong at first.

**Comment by taion** [comment]
It's also documented in the README: https://github.com/relay-tools/react-router-relay/tree/v0.9.0#installation :stuck_out_tongue: 

I do wish the npm error were more prominent, though.

**Comment by KyleAMathews** [comment]
haha, ok this one was on me :P

My problem with NPM I think is it seems there's always some sort of error
so I just skip over the occasional legitimate error like this one.
