### ISSUE TITLE
forceFetch on a route basis

### ISSUE THREAD

**Issue by Globegitter** [relay-tools/react-router-relay#97]
Is there any possibility to have `forceFetch` on a route basis rather than just for the whole sets of routes in an app?

**Comment by taion** [comment]
Not as currently implemented.

**Comment by alexhawkins** [comment]
That would be great!

**Comment by taion** [comment]
This is probably dependent on https://github.com/relay-tools/react-router-relay/issues/68.

**Comment by ohardy** [comment]
Hey, Is it possible now ?

**Comment by taion** [comment]
No.
