### ISSUE TITLE
Can't use the Relay.RootContainer as a component for a route or nest routers inside it.

### ISSUE THREAD

**Issue by DavidEwers** [relay-tools/react-router-relay#98]
The first throws errors, the second won't render children. Since the Relay.RootContainer is especially for fetching data before rendering, I think it should be able to work with react-router-relay. In the relay-starter-kit they use it as the root component where you would put your RelayRouter.

**Comment by taion** [comment]
You appear to be missing the point of this library. Consult the examples.

**Comment by DavidEwers** [comment]
I get it now, you're generating routes automatically and don't need the
relay rootContainer - my apologies. I'm really glad you're project is out
there.
