### ISSUE TITLE
Relay routes side-by-side with no relay routes

### ISSUE THREAD

**Issue by Globegitter** [relay-tools/react-router-relay#99]
I want to be able to have `RelayRouter` routes next to normal `Router` routes side-by-side. So for example my `/login` url should not be within a Relay Rootcontainer. Reason for that is, if we wanted to reset the relay cache we would have to be outside of any Relay context. Any way that is currently possible?

**Comment by taion** [comment]
As it stands, no – just hard-refresh the page if you need to clear the cache. I'm hopeful that upstream changes will make this unnecessary.
